// ***************
// Filename: demo_regs.h
// Author: Paul Barcelona
// Description: C header for register block demo_regs (generated by
//   regmap_gen.py): byte offsets, reset values and field masks.
// Date: 2026-09-29
#ifndef DEMO_REGS_H
#define DEMO_REGS_H
#define DEMO_REGS_ID_OFFSET 0x00u   /* RO */
#define DEMO_REGS_ID_RESET 0x00000000u
#define DEMO_REGS_ID_VALUE_SHIFT 0u
#define DEMO_REGS_ID_VALUE_MASK 0xFFFFFFFFu
#define DEMO_REGS_CTRL_OFFSET 0x04u   /* RW */
#define DEMO_REGS_CTRL_RESET 0x00000010u
#define DEMO_REGS_CTRL_EN_SHIFT 0u
#define DEMO_REGS_CTRL_EN_MASK 0x00000001u
#define DEMO_REGS_CTRL_MODE_SHIFT 1u
#define DEMO_REGS_CTRL_MODE_MASK 0x0000000Eu
#define DEMO_REGS_CTRL_DIV_SHIFT 8u
#define DEMO_REGS_CTRL_DIV_MASK 0x0000FF00u
#define DEMO_REGS_STATUS_OFFSET 0x08u   /* W1C */
#define DEMO_REGS_STATUS_RESET 0x00000000u
#define DEMO_REGS_STATUS_DONE_SHIFT 0u
#define DEMO_REGS_STATUS_DONE_MASK 0x00000001u
#define DEMO_REGS_STATUS_ERR_SHIFT 1u
#define DEMO_REGS_STATUS_ERR_MASK 0x00000002u
#define DEMO_REGS_THRESH_OFFSET 0x0Cu   /* RW */
#define DEMO_REGS_THRESH_RESET 0x00000100u
#define DEMO_REGS_COUNT_OFFSET 0x10u   /* RO */
#define DEMO_REGS_COUNT_RESET 0x00000000u
#define DEMO_REGS_TRIG_OFFSET 0x14u   /* W1S */
#define DEMO_REGS_TRIG_RESET 0x00000000u
#define DEMO_REGS_TRIG_GO_SHIFT 0u
#define DEMO_REGS_TRIG_GO_MASK 0x00000001u
#endif /* DEMO_REGS_H */
