/* Generated by Yosys 0.69+154 (git sha1 30d62572e-dirty, Release, Clang /usr/local/osxcross/target/bin/x86_64-apple-darwin25.5-clang++ 21.1.8) */

module axil_regbus(clk, rst_n, s_axil_awaddr, s_axil_awvalid, s_axil_awready, s_axil_wdata, s_axil_wstrb, s_axil_wvalid, s_axil_wready, s_axil_bresp, s_axil_bvalid, s_axil_bready, s_axil_araddr, s_axil_arvalid, s_axil_arready, s_axil_rdata, s_axil_rresp, s_axil_rvalid, s_axil_rready, reg_wr, reg_waddr
, reg_wdata, reg_wstrb, reg_rd, reg_raddr, reg_rdata);
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  input [15:0] s_axil_awaddr;
  wire [15:0] s_axil_awaddr;
  input s_axil_awvalid;
  wire s_axil_awvalid;
  output s_axil_awready;
  wire s_axil_awready;
  input [31:0] s_axil_wdata;
  wire [31:0] s_axil_wdata;
  input [3:0] s_axil_wstrb;
  wire [3:0] s_axil_wstrb;
  input s_axil_wvalid;
  wire s_axil_wvalid;
  output s_axil_wready;
  wire s_axil_wready;
  output [1:0] s_axil_bresp;
  wire [1:0] s_axil_bresp;
  output s_axil_bvalid;
  wire s_axil_bvalid;
  input s_axil_bready;
  wire s_axil_bready;
  input [15:0] s_axil_araddr;
  wire [15:0] s_axil_araddr;
  input s_axil_arvalid;
  wire s_axil_arvalid;
  output s_axil_arready;
  wire s_axil_arready;
  output [31:0] s_axil_rdata;
  wire [31:0] s_axil_rdata;
  output [1:0] s_axil_rresp;
  wire [1:0] s_axil_rresp;
  output s_axil_rvalid;
  wire s_axil_rvalid;
  input s_axil_rready;
  wire s_axil_rready;
  output reg_wr;
  wire reg_wr;
  output [15:0] reg_waddr;
  wire [15:0] reg_waddr;
  output [31:0] reg_wdata;
  wire [31:0] reg_wdata;
  output [3:0] reg_wstrb;
  wire [3:0] reg_wstrb;
  output reg_rd;
  wire reg_rd;
  output [15:0] reg_raddr;
  wire [15:0] reg_raddr;
  input [31:0] reg_rdata;
  wire [31:0] reg_rdata;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire [3:0] _063_;
  wire [0:0] _064_;
  wire [0:0] _065_;
  wire [0:0] _066_;
  LUT2 #(
    .INIT(4'h1)
  ) _067_ (
    .I0(s_axil_rvalid),
    .I1(_063_[3]),
    .O(s_axil_arready)
  );
  LUT2 #(
    .INIT(4'h2)
  ) _068_ (
    .I0(s_axil_wvalid),
    .I1(_066_),
    .O(_000_)
  );
  LUT3 #(
    .INIT(8'h20)
  ) _069_ (
    .I0(_066_),
    .I1(s_axil_bvalid),
    .I2(_065_),
    .O(_008_)
  );
  LUT3 #(
    .INIT(8'h02)
  ) _070_ (
    .I0(s_axil_arvalid),
    .I1(s_axil_rvalid),
    .I2(_063_[3]),
    .O(_009_)
  );
  LUT2 #(
    .INIT(4'h2)
  ) _071_ (
    .I0(s_axil_awvalid),
    .I1(_065_),
    .O(_003_)
  );
  INV _072_ (
    .I(rst_n),
    .O(_007_)
  );
  INV _073_ (
    .I(_065_),
    .O(s_axil_awready)
  );
  INV _074_ (
    .I(_066_),
    .O(s_axil_wready)
  );
  LUT4 #(
    .INIT(16'haca0)
  ) _075_ (
    .I0(s_axil_bready),
    .I1(_066_),
    .I2(s_axil_bvalid),
    .I3(_065_),
    .O(_005_)
  );
  LUT4 #(
    .INIT(16'h2e22)
  ) _076_ (
    .I0(s_axil_wvalid),
    .I1(_066_),
    .I2(s_axil_bvalid),
    .I3(_065_),
    .O(_004_)
  );
  LUT4 #(
    .INIT(16'h0caa)
  ) _077_ (
    .I0(s_axil_awvalid),
    .I1(_066_),
    .I2(s_axil_bvalid),
    .I3(_065_),
    .O(_002_)
  );
  LUT3 #(
    .INIT(8'hec)
  ) _078_ (
    .I0(s_axil_rready),
    .I1(_064_),
    .I2(s_axil_rvalid),
    .O(_001_)
  );
  LUT3 #(
    .INIT(8'hdf)
  ) _079_ (
    .I0(_066_),
    .I1(s_axil_bvalid),
    .I2(_065_),
    .O(_062_)
  );
  FDCE #(
    .INIT(1'hx)
  ) _080_ (
    .C(clk),
    .CE(_003_),
    .CLR(_007_),
    .D(s_axil_awaddr[0]),
    .Q(_029_)
  );
  FDCE #(
    .INIT(1'hx)
  ) _081_ (
    .C(clk),
    .CE(_003_),
    .CLR(_007_),
    .D(s_axil_awaddr[1]),
    .Q(_028_)
  );
  FDCE #(
    .INIT(1'hx)
  ) _082_ (
    .C(clk),
    .CE(_003_),
    .CLR(_007_),
    .D(s_axil_awaddr[2]),
    .Q(_027_)
  );
  FDCE #(
    .INIT(1'hx)
  ) _083_ (
    .C(clk),
    .CE(_003_),
    .CLR(_007_),
    .D(s_axil_awaddr[3]),
    .Q(_026_)
  );
  FDCE #(
    .INIT(1'hx)
  ) _084_ (
    .C(clk),
    .CE(_003_),
    .CLR(_007_),
    .D(s_axil_awaddr[4]),
    .Q(_025_)
  );
  FDCE #(
    .INIT(1'hx)
  ) _085_ (
    .C(clk),
    .CE(_003_),
    .CLR(_007_),
    .D(s_axil_awaddr[5]),
    .Q(_024_)
  );
  FDCE #(
    .INIT(1'hx)
  ) _086_ (
    .C(clk),
    .CE(_003_),
    .CLR(_007_),
    .D(s_axil_awaddr[6]),
    .Q(_023_)
  );
  FDCE #(
    .INIT(1'hx)
  ) _087_ (
    .C(clk),
    .CE(_003_),
    .CLR(_007_),
    .D(s_axil_awaddr[7]),
    .Q(_022_)
  );
  FDCE #(
    .INIT(1'hx)
  ) _088_ (
    .C(clk),
    .CE(_003_),
    .CLR(_007_),
    .D(s_axil_awaddr[8]),
    .Q(_021_)
  );
  FDCE #(
    .INIT(1'hx)
  ) _089_ (
    .C(clk),
    .CE(_003_),
    .CLR(_007_),
    .D(s_axil_awaddr[9]),
    .Q(_020_)
  );
  FDCE #(
    .INIT(1'hx)
  ) _090_ (
    .C(clk),
    .CE(_003_),
    .CLR(_007_),
    .D(s_axil_awaddr[10]),
    .Q(_019_)
  );
  FDCE #(
    .INIT(1'hx)
  ) _091_ (
    .C(clk),
    .CE(_003_),
    .CLR(_007_),
    .D(s_axil_awaddr[11]),
    .Q(_018_)
  );
  FDCE #(
    .INIT(1'hx)
  ) _092_ (
    .C(clk),
    .CE(_003_),
    .CLR(_007_),
    .D(s_axil_awaddr[12]),
    .Q(_017_)
  );
  FDCE #(
    .INIT(1'hx)
  ) _093_ (
    .C(clk),
    .CE(_003_),
    .CLR(_007_),
    .D(s_axil_awaddr[13]),
    .Q(_016_)
  );
  FDCE #(
    .INIT(1'hx)
  ) _094_ (
    .C(clk),
    .CE(_003_),
    .CLR(_007_),
    .D(s_axil_awaddr[14]),
    .Q(_015_)
  );
  FDCE #(
    .INIT(1'hx)
  ) _095_ (
    .C(clk),
    .CE(_003_),
    .CLR(_007_),
    .D(s_axil_awaddr[15]),
    .Q(_014_)
  );
  FDCE #(
    .INIT(1'hx)
  ) _096_ (
    .C(clk),
    .CE(_005_),
    .CLR(_007_),
    .D(_008_),
    .Q(s_axil_bvalid)
  );
  FDCE #(
    .INIT(1'hx)
  ) _097_ (
    .C(clk),
    .CE(_009_),
    .CLR(_007_),
    .D(s_axil_araddr[0]),
    .Q(reg_raddr[0])
  );
  FDCE #(
    .INIT(1'hx)
  ) _098_ (
    .C(clk),
    .CE(_009_),
    .CLR(_007_),
    .D(s_axil_araddr[1]),
    .Q(reg_raddr[1])
  );
  FDCE #(
    .INIT(1'hx)
  ) _099_ (
    .C(clk),
    .CE(_009_),
    .CLR(_007_),
    .D(s_axil_araddr[2]),
    .Q(reg_raddr[2])
  );
  FDCE #(
    .INIT(1'hx)
  ) _100_ (
    .C(clk),
    .CE(_009_),
    .CLR(_007_),
    .D(s_axil_araddr[3]),
    .Q(reg_raddr[3])
  );
  FDCE #(
    .INIT(1'hx)
  ) _101_ (
    .C(clk),
    .CE(_009_),
    .CLR(_007_),
    .D(s_axil_araddr[4]),
    .Q(reg_raddr[4])
  );
  FDCE #(
    .INIT(1'hx)
  ) _102_ (
    .C(clk),
    .CE(_009_),
    .CLR(_007_),
    .D(s_axil_araddr[5]),
    .Q(reg_raddr[5])
  );
  FDCE #(
    .INIT(1'hx)
  ) _103_ (
    .C(clk),
    .CE(_009_),
    .CLR(_007_),
    .D(s_axil_araddr[6]),
    .Q(reg_raddr[6])
  );
  FDCE #(
    .INIT(1'hx)
  ) _104_ (
    .C(clk),
    .CE(_009_),
    .CLR(_007_),
    .D(s_axil_araddr[7]),
    .Q(reg_raddr[7])
  );
  FDCE #(
    .INIT(1'hx)
  ) _105_ (
    .C(clk),
    .CE(_009_),
    .CLR(_007_),
    .D(s_axil_araddr[8]),
    .Q(reg_raddr[8])
  );
  FDCE #(
    .INIT(1'hx)
  ) _106_ (
    .C(clk),
    .CE(_009_),
    .CLR(_007_),
    .D(s_axil_araddr[9]),
    .Q(reg_raddr[9])
  );
  FDCE #(
    .INIT(1'hx)
  ) _107_ (
    .C(clk),
    .CE(_009_),
    .CLR(_007_),
    .D(s_axil_araddr[10]),
    .Q(reg_raddr[10])
  );
  FDCE #(
    .INIT(1'hx)
  ) _108_ (
    .C(clk),
    .CE(_009_),
    .CLR(_007_),
    .D(s_axil_araddr[11]),
    .Q(reg_raddr[11])
  );
  FDCE #(
    .INIT(1'hx)
  ) _109_ (
    .C(clk),
    .CE(_009_),
    .CLR(_007_),
    .D(s_axil_araddr[12]),
    .Q(reg_raddr[12])
  );
  FDCE #(
    .INIT(1'hx)
  ) _110_ (
    .C(clk),
    .CE(_009_),
    .CLR(_007_),
    .D(s_axil_araddr[13]),
    .Q(reg_raddr[13])
  );
  FDCE #(
    .INIT(1'hx)
  ) _111_ (
    .C(clk),
    .CE(_009_),
    .CLR(_007_),
    .D(s_axil_araddr[14]),
    .Q(reg_raddr[14])
  );
  FDCE #(
    .INIT(1'hx)
  ) _112_ (
    .C(clk),
    .CE(_009_),
    .CLR(_007_),
    .D(s_axil_araddr[15]),
    .Q(reg_raddr[15])
  );
  FDCE #(
    .INIT(1'hx)
  ) _113_ (
    .C(clk),
    .CE(_002_),
    .CLR(_007_),
    .D(_062_),
    .Q(_065_)
  );
  FDCE #(
    .INIT(1'hx)
  ) _114_ (
    .C(clk),
    .CE(_004_),
    .CLR(_007_),
    .D(_062_),
    .Q(_066_)
  );
  FDCE #(
    .INIT(1'hx)
  ) _115_ (
    .C(clk),
    .CE(_000_),
    .CLR(_007_),
    .D(s_axil_wstrb[0]),
    .Q(_013_)
  );
  FDCE #(
    .INIT(1'hx)
  ) _116_ (
    .C(clk),
    .CE(_000_),
    .CLR(_007_),
    .D(s_axil_wstrb[1]),
    .Q(_012_)
  );
  FDCE #(
    .INIT(1'hx)
  ) _117_ (
    .C(clk),
    .CE(_000_),
    .CLR(_007_),
    .D(s_axil_wstrb[2]),
    .Q(_011_)
  );
  FDCE #(
    .INIT(1'hx)
  ) _118_ (
    .C(clk),
    .CE(_000_),
    .CLR(_007_),
    .D(s_axil_wstrb[3]),
    .Q(_010_)
  );
  FDCE #(
    .INIT(1'hx)
  ) _119_ (
    .C(clk),
    .CE(_008_),
    .CLR(_007_),
    .D(_061_),
    .Q(reg_wdata[0])
  );
  FDCE #(
    .INIT(1'hx)
  ) _120_ (
    .C(clk),
    .CE(_008_),
    .CLR(_007_),
    .D(_060_),
    .Q(reg_wdata[1])
  );
  FDCE #(
    .INIT(1'hx)
  ) _121_ (
    .C(clk),
    .CE(_008_),
    .CLR(_007_),
    .D(_059_),
    .Q(reg_wdata[2])
  );
  FDCE #(
    .INIT(1'hx)
  ) _122_ (
    .C(clk),
    .CE(_008_),
    .CLR(_007_),
    .D(_058_),
    .Q(reg_wdata[3])
  );
  FDCE #(
    .INIT(1'hx)
  ) _123_ (
    .C(clk),
    .CE(_008_),
    .CLR(_007_),
    .D(_057_),
    .Q(reg_wdata[4])
  );
  FDCE #(
    .INIT(1'hx)
  ) _124_ (
    .C(clk),
    .CE(_008_),
    .CLR(_007_),
    .D(_056_),
    .Q(reg_wdata[5])
  );
  FDCE #(
    .INIT(1'hx)
  ) _125_ (
    .C(clk),
    .CE(_008_),
    .CLR(_007_),
    .D(_055_),
    .Q(reg_wdata[6])
  );
  FDCE #(
    .INIT(1'hx)
  ) _126_ (
    .C(clk),
    .CE(_008_),
    .CLR(_007_),
    .D(_054_),
    .Q(reg_wdata[7])
  );
  FDCE #(
    .INIT(1'hx)
  ) _127_ (
    .C(clk),
    .CE(_008_),
    .CLR(_007_),
    .D(_053_),
    .Q(reg_wdata[8])
  );
  FDCE #(
    .INIT(1'hx)
  ) _128_ (
    .C(clk),
    .CE(_008_),
    .CLR(_007_),
    .D(_052_),
    .Q(reg_wdata[9])
  );
  FDCE #(
    .INIT(1'hx)
  ) _129_ (
    .C(clk),
    .CE(_008_),
    .CLR(_007_),
    .D(_051_),
    .Q(reg_wdata[10])
  );
  FDCE #(
    .INIT(1'hx)
  ) _130_ (
    .C(clk),
    .CE(_008_),
    .CLR(_007_),
    .D(_050_),
    .Q(reg_wdata[11])
  );
  FDCE #(
    .INIT(1'hx)
  ) _131_ (
    .C(clk),
    .CE(_008_),
    .CLR(_007_),
    .D(_049_),
    .Q(reg_wdata[12])
  );
  FDCE #(
    .INIT(1'hx)
  ) _132_ (
    .C(clk),
    .CE(_008_),
    .CLR(_007_),
    .D(_048_),
    .Q(reg_wdata[13])
  );
  FDCE #(
    .INIT(1'hx)
  ) _133_ (
    .C(clk),
    .CE(_008_),
    .CLR(_007_),
    .D(_047_),
    .Q(reg_wdata[14])
  );
  FDCE #(
    .INIT(1'hx)
  ) _134_ (
    .C(clk),
    .CE(_008_),
    .CLR(_007_),
    .D(_046_),
    .Q(reg_wdata[15])
  );
  FDCE #(
    .INIT(1'hx)
  ) _135_ (
    .C(clk),
    .CE(_008_),
    .CLR(_007_),
    .D(_045_),
    .Q(reg_wdata[16])
  );
  FDCE #(
    .INIT(1'hx)
  ) _136_ (
    .C(clk),
    .CE(_008_),
    .CLR(_007_),
    .D(_044_),
    .Q(reg_wdata[17])
  );
  FDCE #(
    .INIT(1'hx)
  ) _137_ (
    .C(clk),
    .CE(_008_),
    .CLR(_007_),
    .D(_043_),
    .Q(reg_wdata[18])
  );
  FDCE #(
    .INIT(1'hx)
  ) _138_ (
    .C(clk),
    .CE(_008_),
    .CLR(_007_),
    .D(_042_),
    .Q(reg_wdata[19])
  );
  FDCE #(
    .INIT(1'hx)
  ) _139_ (
    .C(clk),
    .CE(_008_),
    .CLR(_007_),
    .D(_041_),
    .Q(reg_wdata[20])
  );
  FDCE #(
    .INIT(1'hx)
  ) _140_ (
    .C(clk),
    .CE(_008_),
    .CLR(_007_),
    .D(_040_),
    .Q(reg_wdata[21])
  );
  FDCE #(
    .INIT(1'hx)
  ) _141_ (
    .C(clk),
    .CE(_008_),
    .CLR(_007_),
    .D(_039_),
    .Q(reg_wdata[22])
  );
  FDCE #(
    .INIT(1'hx)
  ) _142_ (
    .C(clk),
    .CE(_008_),
    .CLR(_007_),
    .D(_038_),
    .Q(reg_wdata[23])
  );
  FDCE #(
    .INIT(1'hx)
  ) _143_ (
    .C(clk),
    .CE(_008_),
    .CLR(_007_),
    .D(_037_),
    .Q(reg_wdata[24])
  );
  FDCE #(
    .INIT(1'hx)
  ) _144_ (
    .C(clk),
    .CE(_008_),
    .CLR(_007_),
    .D(_036_),
    .Q(reg_wdata[25])
  );
  FDCE #(
    .INIT(1'hx)
  ) _145_ (
    .C(clk),
    .CE(_008_),
    .CLR(_007_),
    .D(_035_),
    .Q(reg_wdata[26])
  );
  FDCE #(
    .INIT(1'hx)
  ) _146_ (
    .C(clk),
    .CE(_008_),
    .CLR(_007_),
    .D(_034_),
    .Q(reg_wdata[27])
  );
  FDCE #(
    .INIT(1'hx)
  ) _147_ (
    .C(clk),
    .CE(_008_),
    .CLR(_007_),
    .D(_033_),
    .Q(reg_wdata[28])
  );
  FDCE #(
    .INIT(1'hx)
  ) _148_ (
    .C(clk),
    .CE(_008_),
    .CLR(_007_),
    .D(_032_),
    .Q(reg_wdata[29])
  );
  FDCE #(
    .INIT(1'hx)
  ) _149_ (
    .C(clk),
    .CE(_008_),
    .CLR(_007_),
    .D(_031_),
    .Q(reg_wdata[30])
  );
  FDCE #(
    .INIT(1'hx)
  ) _150_ (
    .C(clk),
    .CE(_008_),
    .CLR(_007_),
    .D(_030_),
    .Q(reg_wdata[31])
  );
  FDCE #(
    .INIT(1'hx)
  ) _151_ (
    .C(clk),
    .CE(_001_),
    .CLR(_007_),
    .D(_064_),
    .Q(s_axil_rvalid)
  );
  FDCE #(
    .INIT(1'hx)
  ) _152_ (
    .C(clk),
    .CE(_008_),
    .CLR(_007_),
    .D(_029_),
    .Q(reg_waddr[0])
  );
  FDCE #(
    .INIT(1'hx)
  ) _153_ (
    .C(clk),
    .CE(_008_),
    .CLR(_007_),
    .D(_028_),
    .Q(reg_waddr[1])
  );
  FDCE #(
    .INIT(1'hx)
  ) _154_ (
    .C(clk),
    .CE(_008_),
    .CLR(_007_),
    .D(_027_),
    .Q(reg_waddr[2])
  );
  FDCE #(
    .INIT(1'hx)
  ) _155_ (
    .C(clk),
    .CE(_008_),
    .CLR(_007_),
    .D(_026_),
    .Q(reg_waddr[3])
  );
  FDCE #(
    .INIT(1'hx)
  ) _156_ (
    .C(clk),
    .CE(_008_),
    .CLR(_007_),
    .D(_025_),
    .Q(reg_waddr[4])
  );
  FDCE #(
    .INIT(1'hx)
  ) _157_ (
    .C(clk),
    .CE(_008_),
    .CLR(_007_),
    .D(_024_),
    .Q(reg_waddr[5])
  );
  FDCE #(
    .INIT(1'hx)
  ) _158_ (
    .C(clk),
    .CE(_008_),
    .CLR(_007_),
    .D(_023_),
    .Q(reg_waddr[6])
  );
  FDCE #(
    .INIT(1'hx)
  ) _159_ (
    .C(clk),
    .CE(_008_),
    .CLR(_007_),
    .D(_022_),
    .Q(reg_waddr[7])
  );
  FDCE #(
    .INIT(1'hx)
  ) _160_ (
    .C(clk),
    .CE(_008_),
    .CLR(_007_),
    .D(_021_),
    .Q(reg_waddr[8])
  );
  FDCE #(
    .INIT(1'hx)
  ) _161_ (
    .C(clk),
    .CE(_008_),
    .CLR(_007_),
    .D(_020_),
    .Q(reg_waddr[9])
  );
  FDCE #(
    .INIT(1'hx)
  ) _162_ (
    .C(clk),
    .CE(_008_),
    .CLR(_007_),
    .D(_019_),
    .Q(reg_waddr[10])
  );
  FDCE #(
    .INIT(1'hx)
  ) _163_ (
    .C(clk),
    .CE(_008_),
    .CLR(_007_),
    .D(_018_),
    .Q(reg_waddr[11])
  );
  FDCE #(
    .INIT(1'hx)
  ) _164_ (
    .C(clk),
    .CE(_008_),
    .CLR(_007_),
    .D(_017_),
    .Q(reg_waddr[12])
  );
  FDCE #(
    .INIT(1'hx)
  ) _165_ (
    .C(clk),
    .CE(_008_),
    .CLR(_007_),
    .D(_016_),
    .Q(reg_waddr[13])
  );
  FDCE #(
    .INIT(1'hx)
  ) _166_ (
    .C(clk),
    .CE(_008_),
    .CLR(_007_),
    .D(_015_),
    .Q(reg_waddr[14])
  );
  FDCE #(
    .INIT(1'hx)
  ) _167_ (
    .C(clk),
    .CE(_008_),
    .CLR(_007_),
    .D(_014_),
    .Q(reg_waddr[15])
  );
  FDCE #(
    .INIT(1'hx)
  ) _168_ (
    .C(clk),
    .CE(_064_),
    .CLR(_007_),
    .D(reg_rdata[0]),
    .Q(s_axil_rdata[0])
  );
  FDCE #(
    .INIT(1'hx)
  ) _169_ (
    .C(clk),
    .CE(_064_),
    .CLR(_007_),
    .D(reg_rdata[1]),
    .Q(s_axil_rdata[1])
  );
  FDCE #(
    .INIT(1'hx)
  ) _170_ (
    .C(clk),
    .CE(_064_),
    .CLR(_007_),
    .D(reg_rdata[2]),
    .Q(s_axil_rdata[2])
  );
  FDCE #(
    .INIT(1'hx)
  ) _171_ (
    .C(clk),
    .CE(_064_),
    .CLR(_007_),
    .D(reg_rdata[3]),
    .Q(s_axil_rdata[3])
  );
  FDCE #(
    .INIT(1'hx)
  ) _172_ (
    .C(clk),
    .CE(_064_),
    .CLR(_007_),
    .D(reg_rdata[4]),
    .Q(s_axil_rdata[4])
  );
  FDCE #(
    .INIT(1'hx)
  ) _173_ (
    .C(clk),
    .CE(_064_),
    .CLR(_007_),
    .D(reg_rdata[5]),
    .Q(s_axil_rdata[5])
  );
  FDCE #(
    .INIT(1'hx)
  ) _174_ (
    .C(clk),
    .CE(_064_),
    .CLR(_007_),
    .D(reg_rdata[6]),
    .Q(s_axil_rdata[6])
  );
  FDCE #(
    .INIT(1'hx)
  ) _175_ (
    .C(clk),
    .CE(_064_),
    .CLR(_007_),
    .D(reg_rdata[7]),
    .Q(s_axil_rdata[7])
  );
  FDCE #(
    .INIT(1'hx)
  ) _176_ (
    .C(clk),
    .CE(_064_),
    .CLR(_007_),
    .D(reg_rdata[8]),
    .Q(s_axil_rdata[8])
  );
  FDCE #(
    .INIT(1'hx)
  ) _177_ (
    .C(clk),
    .CE(_064_),
    .CLR(_007_),
    .D(reg_rdata[9]),
    .Q(s_axil_rdata[9])
  );
  FDCE #(
    .INIT(1'hx)
  ) _178_ (
    .C(clk),
    .CE(_064_),
    .CLR(_007_),
    .D(reg_rdata[10]),
    .Q(s_axil_rdata[10])
  );
  FDCE #(
    .INIT(1'hx)
  ) _179_ (
    .C(clk),
    .CE(_064_),
    .CLR(_007_),
    .D(reg_rdata[11]),
    .Q(s_axil_rdata[11])
  );
  FDCE #(
    .INIT(1'hx)
  ) _180_ (
    .C(clk),
    .CE(_064_),
    .CLR(_007_),
    .D(reg_rdata[12]),
    .Q(s_axil_rdata[12])
  );
  FDCE #(
    .INIT(1'hx)
  ) _181_ (
    .C(clk),
    .CE(_064_),
    .CLR(_007_),
    .D(reg_rdata[13]),
    .Q(s_axil_rdata[13])
  );
  FDCE #(
    .INIT(1'hx)
  ) _182_ (
    .C(clk),
    .CE(_064_),
    .CLR(_007_),
    .D(reg_rdata[14]),
    .Q(s_axil_rdata[14])
  );
  FDCE #(
    .INIT(1'hx)
  ) _183_ (
    .C(clk),
    .CE(_064_),
    .CLR(_007_),
    .D(reg_rdata[15]),
    .Q(s_axil_rdata[15])
  );
  FDCE #(
    .INIT(1'hx)
  ) _184_ (
    .C(clk),
    .CE(_064_),
    .CLR(_007_),
    .D(reg_rdata[16]),
    .Q(s_axil_rdata[16])
  );
  FDCE #(
    .INIT(1'hx)
  ) _185_ (
    .C(clk),
    .CE(_064_),
    .CLR(_007_),
    .D(reg_rdata[17]),
    .Q(s_axil_rdata[17])
  );
  FDCE #(
    .INIT(1'hx)
  ) _186_ (
    .C(clk),
    .CE(_064_),
    .CLR(_007_),
    .D(reg_rdata[18]),
    .Q(s_axil_rdata[18])
  );
  FDCE #(
    .INIT(1'hx)
  ) _187_ (
    .C(clk),
    .CE(_064_),
    .CLR(_007_),
    .D(reg_rdata[19]),
    .Q(s_axil_rdata[19])
  );
  FDCE #(
    .INIT(1'hx)
  ) _188_ (
    .C(clk),
    .CE(_064_),
    .CLR(_007_),
    .D(reg_rdata[20]),
    .Q(s_axil_rdata[20])
  );
  FDCE #(
    .INIT(1'hx)
  ) _189_ (
    .C(clk),
    .CE(_064_),
    .CLR(_007_),
    .D(reg_rdata[21]),
    .Q(s_axil_rdata[21])
  );
  FDCE #(
    .INIT(1'hx)
  ) _190_ (
    .C(clk),
    .CE(_064_),
    .CLR(_007_),
    .D(reg_rdata[22]),
    .Q(s_axil_rdata[22])
  );
  FDCE #(
    .INIT(1'hx)
  ) _191_ (
    .C(clk),
    .CE(_064_),
    .CLR(_007_),
    .D(reg_rdata[23]),
    .Q(s_axil_rdata[23])
  );
  FDCE #(
    .INIT(1'hx)
  ) _192_ (
    .C(clk),
    .CE(_064_),
    .CLR(_007_),
    .D(reg_rdata[24]),
    .Q(s_axil_rdata[24])
  );
  FDCE #(
    .INIT(1'hx)
  ) _193_ (
    .C(clk),
    .CE(_064_),
    .CLR(_007_),
    .D(reg_rdata[25]),
    .Q(s_axil_rdata[25])
  );
  FDCE #(
    .INIT(1'hx)
  ) _194_ (
    .C(clk),
    .CE(_064_),
    .CLR(_007_),
    .D(reg_rdata[26]),
    .Q(s_axil_rdata[26])
  );
  FDCE #(
    .INIT(1'hx)
  ) _195_ (
    .C(clk),
    .CE(_064_),
    .CLR(_007_),
    .D(reg_rdata[27]),
    .Q(s_axil_rdata[27])
  );
  FDCE #(
    .INIT(1'hx)
  ) _196_ (
    .C(clk),
    .CE(_064_),
    .CLR(_007_),
    .D(reg_rdata[28]),
    .Q(s_axil_rdata[28])
  );
  FDCE #(
    .INIT(1'hx)
  ) _197_ (
    .C(clk),
    .CE(_064_),
    .CLR(_007_),
    .D(reg_rdata[29]),
    .Q(s_axil_rdata[29])
  );
  FDCE #(
    .INIT(1'hx)
  ) _198_ (
    .C(clk),
    .CE(_064_),
    .CLR(_007_),
    .D(reg_rdata[30]),
    .Q(s_axil_rdata[30])
  );
  FDCE #(
    .INIT(1'hx)
  ) _199_ (
    .C(clk),
    .CE(_064_),
    .CLR(_007_),
    .D(reg_rdata[31]),
    .Q(s_axil_rdata[31])
  );
  FDCE #(
    .INIT(1'hx)
  ) _200_ (
    .C(clk),
    .CE(_008_),
    .CLR(_007_),
    .D(_013_),
    .Q(reg_wstrb[0])
  );
  FDCE #(
    .INIT(1'hx)
  ) _201_ (
    .C(clk),
    .CE(_008_),
    .CLR(_007_),
    .D(_012_),
    .Q(reg_wstrb[1])
  );
  FDCE #(
    .INIT(1'hx)
  ) _202_ (
    .C(clk),
    .CE(_008_),
    .CLR(_007_),
    .D(_011_),
    .Q(reg_wstrb[2])
  );
  FDCE #(
    .INIT(1'hx)
  ) _203_ (
    .C(clk),
    .CE(_008_),
    .CLR(_007_),
    .D(_010_),
    .Q(reg_wstrb[3])
  );
  FDCE #(
    .INIT(1'hx)
  ) _204_ (
    .C(clk),
    .CE(_000_),
    .CLR(_007_),
    .D(s_axil_wdata[0]),
    .Q(_061_)
  );
  FDCE #(
    .INIT(1'hx)
  ) _205_ (
    .C(clk),
    .CE(_000_),
    .CLR(_007_),
    .D(s_axil_wdata[1]),
    .Q(_060_)
  );
  FDCE #(
    .INIT(1'hx)
  ) _206_ (
    .C(clk),
    .CE(_000_),
    .CLR(_007_),
    .D(s_axil_wdata[2]),
    .Q(_059_)
  );
  FDCE #(
    .INIT(1'hx)
  ) _207_ (
    .C(clk),
    .CE(_000_),
    .CLR(_007_),
    .D(s_axil_wdata[3]),
    .Q(_058_)
  );
  FDCE #(
    .INIT(1'hx)
  ) _208_ (
    .C(clk),
    .CE(_000_),
    .CLR(_007_),
    .D(s_axil_wdata[4]),
    .Q(_057_)
  );
  FDCE #(
    .INIT(1'hx)
  ) _209_ (
    .C(clk),
    .CE(_000_),
    .CLR(_007_),
    .D(s_axil_wdata[5]),
    .Q(_056_)
  );
  FDCE #(
    .INIT(1'hx)
  ) _210_ (
    .C(clk),
    .CE(_000_),
    .CLR(_007_),
    .D(s_axil_wdata[6]),
    .Q(_055_)
  );
  FDCE #(
    .INIT(1'hx)
  ) _211_ (
    .C(clk),
    .CE(_000_),
    .CLR(_007_),
    .D(s_axil_wdata[7]),
    .Q(_054_)
  );
  FDCE #(
    .INIT(1'hx)
  ) _212_ (
    .C(clk),
    .CE(_000_),
    .CLR(_007_),
    .D(s_axil_wdata[8]),
    .Q(_053_)
  );
  FDCE #(
    .INIT(1'hx)
  ) _213_ (
    .C(clk),
    .CE(_000_),
    .CLR(_007_),
    .D(s_axil_wdata[9]),
    .Q(_052_)
  );
  FDCE #(
    .INIT(1'hx)
  ) _214_ (
    .C(clk),
    .CE(_000_),
    .CLR(_007_),
    .D(s_axil_wdata[10]),
    .Q(_051_)
  );
  FDCE #(
    .INIT(1'hx)
  ) _215_ (
    .C(clk),
    .CE(_000_),
    .CLR(_007_),
    .D(s_axil_wdata[11]),
    .Q(_050_)
  );
  FDCE #(
    .INIT(1'hx)
  ) _216_ (
    .C(clk),
    .CE(_000_),
    .CLR(_007_),
    .D(s_axil_wdata[12]),
    .Q(_049_)
  );
  FDCE #(
    .INIT(1'hx)
  ) _217_ (
    .C(clk),
    .CE(_000_),
    .CLR(_007_),
    .D(s_axil_wdata[13]),
    .Q(_048_)
  );
  FDCE #(
    .INIT(1'hx)
  ) _218_ (
    .C(clk),
    .CE(_000_),
    .CLR(_007_),
    .D(s_axil_wdata[14]),
    .Q(_047_)
  );
  FDCE #(
    .INIT(1'hx)
  ) _219_ (
    .C(clk),
    .CE(_000_),
    .CLR(_007_),
    .D(s_axil_wdata[15]),
    .Q(_046_)
  );
  FDCE #(
    .INIT(1'hx)
  ) _220_ (
    .C(clk),
    .CE(_000_),
    .CLR(_007_),
    .D(s_axil_wdata[16]),
    .Q(_045_)
  );
  FDCE #(
    .INIT(1'hx)
  ) _221_ (
    .C(clk),
    .CE(_000_),
    .CLR(_007_),
    .D(s_axil_wdata[17]),
    .Q(_044_)
  );
  FDCE #(
    .INIT(1'hx)
  ) _222_ (
    .C(clk),
    .CE(_000_),
    .CLR(_007_),
    .D(s_axil_wdata[18]),
    .Q(_043_)
  );
  FDCE #(
    .INIT(1'hx)
  ) _223_ (
    .C(clk),
    .CE(_000_),
    .CLR(_007_),
    .D(s_axil_wdata[19]),
    .Q(_042_)
  );
  FDCE #(
    .INIT(1'hx)
  ) _224_ (
    .C(clk),
    .CE(_000_),
    .CLR(_007_),
    .D(s_axil_wdata[20]),
    .Q(_041_)
  );
  FDCE #(
    .INIT(1'hx)
  ) _225_ (
    .C(clk),
    .CE(_000_),
    .CLR(_007_),
    .D(s_axil_wdata[21]),
    .Q(_040_)
  );
  FDCE #(
    .INIT(1'hx)
  ) _226_ (
    .C(clk),
    .CE(_000_),
    .CLR(_007_),
    .D(s_axil_wdata[22]),
    .Q(_039_)
  );
  FDCE #(
    .INIT(1'hx)
  ) _227_ (
    .C(clk),
    .CE(_000_),
    .CLR(_007_),
    .D(s_axil_wdata[23]),
    .Q(_038_)
  );
  FDCE #(
    .INIT(1'hx)
  ) _228_ (
    .C(clk),
    .CE(_000_),
    .CLR(_007_),
    .D(s_axil_wdata[24]),
    .Q(_037_)
  );
  FDCE #(
    .INIT(1'hx)
  ) _229_ (
    .C(clk),
    .CE(_000_),
    .CLR(_007_),
    .D(s_axil_wdata[25]),
    .Q(_036_)
  );
  FDCE #(
    .INIT(1'hx)
  ) _230_ (
    .C(clk),
    .CE(_000_),
    .CLR(_007_),
    .D(s_axil_wdata[26]),
    .Q(_035_)
  );
  FDCE #(
    .INIT(1'hx)
  ) _231_ (
    .C(clk),
    .CE(_000_),
    .CLR(_007_),
    .D(s_axil_wdata[27]),
    .Q(_034_)
  );
  FDCE #(
    .INIT(1'hx)
  ) _232_ (
    .C(clk),
    .CE(_000_),
    .CLR(_007_),
    .D(s_axil_wdata[28]),
    .Q(_033_)
  );
  FDCE #(
    .INIT(1'hx)
  ) _233_ (
    .C(clk),
    .CE(_000_),
    .CLR(_007_),
    .D(s_axil_wdata[29]),
    .Q(_032_)
  );
  FDCE #(
    .INIT(1'hx)
  ) _234_ (
    .C(clk),
    .CE(_000_),
    .CLR(_007_),
    .D(s_axil_wdata[30]),
    .Q(_031_)
  );
  FDCE #(
    .INIT(1'hx)
  ) _235_ (
    .C(clk),
    .CE(_000_),
    .CLR(_007_),
    .D(s_axil_wdata[31]),
    .Q(_030_)
  );
  FDCE #(
    .INIT(1'hx)
  ) _236_ (
    .C(clk),
    .CE(1'h1),
    .CLR(_007_),
    .D(_006_),
    .Q(_063_[3])
  );
  FDCE #(
    .INIT(1'hx)
  ) _237_ (
    .C(clk),
    .CE(1'h1),
    .CLR(_007_),
    .D(_009_),
    .Q(reg_rd)
  );
  FDCE #(
    .INIT(1'hx)
  ) _238_ (
    .C(clk),
    .CE(1'h1),
    .CLR(_007_),
    .D(reg_rd),
    .Q(_064_)
  );
  FDCE #(
    .INIT(1'hx)
  ) _239_ (
    .C(clk),
    .CE(1'h1),
    .CLR(_007_),
    .D(_008_),
    .Q(reg_wr)
  );
  LUT4 #(
    .INIT(16'h00ba)
  ) _240_ (
    .I0(_063_[3]),
    .I1(s_axil_rvalid),
    .I2(s_axil_arvalid),
    .I3(_064_),
    .O(_006_)
  );
  assign _063_[2:0] = { s_axil_rvalid, _064_, s_axil_arvalid };
  assign s_axil_bresp = 2'h0;
  assign s_axil_rresp = 2'h0;
endmodule
