/* Generated by Yosys 0.69+154 (git sha1 30d62572e-dirty, Release, Clang /usr/local/osxcross/target/bin/x86_64-apple-darwin25.5-clang++ 21.1.8) */

module axil_split(clk, rst_n, s_awaddr, s_awvalid, s_awready, s_wdata, s_wstrb, s_wvalid, s_wready, s_bresp, s_bvalid, s_bready, s_araddr, s_arvalid, s_arready, s_rdata, s_rresp, s_rvalid, s_rready, m_awaddr, m_awvalid
, m_awready, m_wdata, m_wstrb, m_wvalid, m_wready, m_bresp, m_bvalid, m_bready, m_araddr, m_arvalid, m_arready, m_rdata, m_rresp, m_rvalid, m_rready);
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  input [14:0] s_awaddr;
  wire [14:0] s_awaddr;
  input s_awvalid;
  wire s_awvalid;
  output s_awready;
  wire s_awready;
  input [31:0] s_wdata;
  wire [31:0] s_wdata;
  input [3:0] s_wstrb;
  wire [3:0] s_wstrb;
  input s_wvalid;
  wire s_wvalid;
  output s_wready;
  wire s_wready;
  output [1:0] s_bresp;
  wire [1:0] s_bresp;
  output s_bvalid;
  wire s_bvalid;
  input s_bready;
  wire s_bready;
  input [14:0] s_araddr;
  wire [14:0] s_araddr;
  input s_arvalid;
  wire s_arvalid;
  output s_arready;
  wire s_arready;
  output [31:0] s_rdata;
  wire [31:0] s_rdata;
  output [1:0] s_rresp;
  wire [1:0] s_rresp;
  output s_rvalid;
  wire s_rvalid;
  input s_rready;
  wire s_rready;
  output [29:0] m_awaddr;
  wire [29:0] m_awaddr;
  output [1:0] m_awvalid;
  wire [1:0] m_awvalid;
  input [1:0] m_awready;
  wire [1:0] m_awready;
  output [63:0] m_wdata;
  wire [63:0] m_wdata;
  output [7:0] m_wstrb;
  wire [7:0] m_wstrb;
  output [1:0] m_wvalid;
  wire [1:0] m_wvalid;
  input [1:0] m_wready;
  wire [1:0] m_wready;
  input [3:0] m_bresp;
  wire [3:0] m_bresp;
  input [1:0] m_bvalid;
  wire [1:0] m_bvalid;
  output [1:0] m_bready;
  wire [1:0] m_bready;
  output [29:0] m_araddr;
  wire [29:0] m_araddr;
  output [1:0] m_arvalid;
  wire [1:0] m_arvalid;
  input [1:0] m_arready;
  wire [1:0] m_arready;
  input [63:0] m_rdata;
  wire [63:0] m_rdata;
  input [3:0] m_rresp;
  wire [3:0] m_rresp;
  input [1:0] m_rvalid;
  wire [1:0] m_rvalid;
  output [1:0] m_rready;
  wire [1:0] m_rready;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire [3:0] _054_;
  wire [2:0] _055_;
  wire [4:0] _056_;
  wire [2:0] _057_;
  wire [4:0] _058_;
  wire [4:0] _059_;
  wire [3:0] _060_;
  wire [2:0] _061_;
  wire [4:0] _062_;
  wire [3:0] _063_;
  wire [3:0] _064_;
  wire [2:0] _065_;
  wire [2:0] _066_;
  wire [0:0] _067_;
  wire [0:0] _068_;
  wire [1:0] _069_;
  wire [1:0] _070_;
  wire [3:0] _071_;
  wire [3:0] _072_;
  LUT2 #(
    .INIT(4'h8)
  ) _073_ (
    .I0(s_arvalid),
    .I1(s_arready),
    .O(_059_[4])
  );
  LUT2 #(
    .INIT(4'h8)
  ) _074_ (
    .I0(s_wvalid),
    .I1(s_wready),
    .O(_072_[3])
  );
  LUT4 #(
    .INIT(16'h00b8)
  ) _075_ (
    .I0(s_bready),
    .I1(_067_),
    .I2(_060_[2]),
    .I3(_065_[0]),
    .O(_000_)
  );
  LUT3 #(
    .INIT(8'he2)
  ) _076_ (
    .I0(s_awaddr[14]),
    .I1(_056_[3]),
    .I2(m_awaddr[14]),
    .O(_020_)
  );
  LUT5 #(
    .INIT(32'd4207411200)
  ) _077_ (
    .I0(s_wvalid),
    .I1(s_awvalid),
    .I2(_056_[2]),
    .I3(_056_[3]),
    .I4(_056_[4]),
    .O(_057_[2])
  );
  LUT2 #(
    .INIT(4'h8)
  ) _078_ (
    .I0(s_awvalid),
    .I1(s_awready),
    .O(_071_[3])
  );
  LUT3 #(
    .INIT(8'hac)
  ) _079_ (
    .I0(m_rdata[33]),
    .I1(m_rdata[1]),
    .I2(m_araddr[14]),
    .O(_052_)
  );
  LUT4 #(
    .INIT(16'ha0c0)
  ) _080_ (
    .I0(m_rvalid[1]),
    .I1(m_rvalid[0]),
    .I2(_054_[2]),
    .I3(m_araddr[14]),
    .O(_055_[2])
  );
  LUT5 #(
    .INIT(32'd4210819072)
  ) _081_ (
    .I0(m_wready[1]),
    .I1(m_wready[0]),
    .I2(_062_[2]),
    .I3(_060_[3]),
    .I4(_057_[1]),
    .O(_021_)
  );
  LUT3 #(
    .INIT(8'hac)
  ) _082_ (
    .I0(m_rdata[63]),
    .I1(m_rdata[31]),
    .I2(m_araddr[14]),
    .O(_022_)
  );
  LUT3 #(
    .INIT(8'hac)
  ) _083_ (
    .I0(m_rdata[62]),
    .I1(m_rdata[30]),
    .I2(m_araddr[14]),
    .O(_023_)
  );
  LUT3 #(
    .INIT(8'hac)
  ) _084_ (
    .I0(m_rdata[61]),
    .I1(m_rdata[29]),
    .I2(m_araddr[14]),
    .O(_024_)
  );
  LUT3 #(
    .INIT(8'hac)
  ) _085_ (
    .I0(m_rdata[60]),
    .I1(m_rdata[28]),
    .I2(m_araddr[14]),
    .O(_025_)
  );
  LUT3 #(
    .INIT(8'hac)
  ) _086_ (
    .I0(m_rdata[59]),
    .I1(m_rdata[27]),
    .I2(m_araddr[14]),
    .O(_026_)
  );
  LUT3 #(
    .INIT(8'hac)
  ) _087_ (
    .I0(m_rdata[58]),
    .I1(m_rdata[26]),
    .I2(m_araddr[14]),
    .O(_027_)
  );
  LUT3 #(
    .INIT(8'hac)
  ) _088_ (
    .I0(m_rdata[57]),
    .I1(m_rdata[25]),
    .I2(m_araddr[14]),
    .O(_028_)
  );
  LUT3 #(
    .INIT(8'hac)
  ) _089_ (
    .I0(m_rdata[56]),
    .I1(m_rdata[24]),
    .I2(m_araddr[14]),
    .O(_029_)
  );
  LUT3 #(
    .INIT(8'hac)
  ) _090_ (
    .I0(m_rdata[55]),
    .I1(m_rdata[23]),
    .I2(m_araddr[14]),
    .O(_030_)
  );
  LUT3 #(
    .INIT(8'hac)
  ) _091_ (
    .I0(m_rdata[54]),
    .I1(m_rdata[22]),
    .I2(m_araddr[14]),
    .O(_031_)
  );
  LUT3 #(
    .INIT(8'hac)
  ) _092_ (
    .I0(m_rdata[53]),
    .I1(m_rdata[21]),
    .I2(m_araddr[14]),
    .O(_032_)
  );
  LUT3 #(
    .INIT(8'hac)
  ) _093_ (
    .I0(m_rdata[52]),
    .I1(m_rdata[20]),
    .I2(m_araddr[14]),
    .O(_033_)
  );
  LUT3 #(
    .INIT(8'hac)
  ) _094_ (
    .I0(m_rdata[51]),
    .I1(m_rdata[19]),
    .I2(m_araddr[14]),
    .O(_034_)
  );
  LUT3 #(
    .INIT(8'hac)
  ) _095_ (
    .I0(m_rdata[50]),
    .I1(m_rdata[18]),
    .I2(m_araddr[14]),
    .O(_035_)
  );
  LUT3 #(
    .INIT(8'hac)
  ) _096_ (
    .I0(m_rdata[49]),
    .I1(m_rdata[17]),
    .I2(m_araddr[14]),
    .O(_036_)
  );
  LUT3 #(
    .INIT(8'hac)
  ) _097_ (
    .I0(m_rdata[48]),
    .I1(m_rdata[16]),
    .I2(m_araddr[14]),
    .O(_037_)
  );
  LUT3 #(
    .INIT(8'hac)
  ) _098_ (
    .I0(m_rdata[47]),
    .I1(m_rdata[15]),
    .I2(m_araddr[14]),
    .O(_038_)
  );
  LUT3 #(
    .INIT(8'hac)
  ) _099_ (
    .I0(m_rdata[46]),
    .I1(m_rdata[14]),
    .I2(m_araddr[14]),
    .O(_039_)
  );
  LUT3 #(
    .INIT(8'hac)
  ) _100_ (
    .I0(m_rdata[45]),
    .I1(m_rdata[13]),
    .I2(m_araddr[14]),
    .O(_040_)
  );
  LUT3 #(
    .INIT(8'hac)
  ) _101_ (
    .I0(m_rdata[44]),
    .I1(m_rdata[12]),
    .I2(m_araddr[14]),
    .O(_041_)
  );
  LUT3 #(
    .INIT(8'hac)
  ) _102_ (
    .I0(m_rdata[43]),
    .I1(m_rdata[11]),
    .I2(m_araddr[14]),
    .O(_042_)
  );
  LUT3 #(
    .INIT(8'hac)
  ) _103_ (
    .I0(m_rdata[42]),
    .I1(m_rdata[10]),
    .I2(m_araddr[14]),
    .O(_043_)
  );
  LUT3 #(
    .INIT(8'hac)
  ) _104_ (
    .I0(m_rdata[41]),
    .I1(m_rdata[9]),
    .I2(m_araddr[14]),
    .O(_044_)
  );
  LUT3 #(
    .INIT(8'hac)
  ) _105_ (
    .I0(m_rdata[40]),
    .I1(m_rdata[8]),
    .I2(m_araddr[14]),
    .O(_045_)
  );
  LUT3 #(
    .INIT(8'hac)
  ) _106_ (
    .I0(m_rdata[39]),
    .I1(m_rdata[7]),
    .I2(m_araddr[14]),
    .O(_046_)
  );
  LUT3 #(
    .INIT(8'hac)
  ) _107_ (
    .I0(m_rdata[38]),
    .I1(m_rdata[6]),
    .I2(m_araddr[14]),
    .O(_047_)
  );
  LUT3 #(
    .INIT(8'hac)
  ) _108_ (
    .I0(m_rdata[37]),
    .I1(m_rdata[5]),
    .I2(m_araddr[14]),
    .O(_048_)
  );
  LUT3 #(
    .INIT(8'hac)
  ) _109_ (
    .I0(m_rdata[36]),
    .I1(m_rdata[4]),
    .I2(m_araddr[14]),
    .O(_049_)
  );
  LUT3 #(
    .INIT(8'hac)
  ) _110_ (
    .I0(m_rdata[35]),
    .I1(m_rdata[3]),
    .I2(m_araddr[14]),
    .O(_050_)
  );
  LUT3 #(
    .INIT(8'hac)
  ) _111_ (
    .I0(m_rdata[34]),
    .I1(m_rdata[2]),
    .I2(m_araddr[14]),
    .O(_051_)
  );
  LUT4 #(
    .INIT(16'hb808)
  ) _112_ (
    .I0(s_bready),
    .I1(_067_),
    .I2(_056_[4]),
    .I3(_072_[3]),
    .O(_002_)
  );
  LUT3 #(
    .INIT(8'hac)
  ) _113_ (
    .I0(m_rresp[3]),
    .I1(m_rresp[1]),
    .I2(m_araddr[14]),
    .O(_015_)
  );
  LUT3 #(
    .INIT(8'hac)
  ) _114_ (
    .I0(m_rresp[2]),
    .I1(m_rresp[0]),
    .I2(m_araddr[14]),
    .O(_016_)
  );
  LUT3 #(
    .INIT(8'hac)
  ) _115_ (
    .I0(m_bresp[3]),
    .I1(m_bresp[1]),
    .I2(_060_[3]),
    .O(_018_)
  );
  LUT4 #(
    .INIT(16'ha0c0)
  ) _116_ (
    .I0(m_bvalid[1]),
    .I1(m_bvalid[0]),
    .I2(_060_[2]),
    .I3(_060_[3]),
    .O(_061_[2])
  );
  LUT3 #(
    .INIT(8'hac)
  ) _117_ (
    .I0(m_bresp[2]),
    .I1(m_bresp[0]),
    .I2(_060_[3]),
    .O(_019_)
  );
  LUT4 #(
    .INIT(16'hb808)
  ) _118_ (
    .I0(s_bready),
    .I1(_067_),
    .I2(_056_[4]),
    .I3(_071_[3]),
    .O(_003_)
  );
  LUT3 #(
    .INIT(8'hac)
  ) _119_ (
    .I0(m_rdata[32]),
    .I1(m_rdata[0]),
    .I2(m_araddr[14]),
    .O(_053_)
  );
  LUT2 #(
    .INIT(4'h2)
  ) _120_ (
    .I0(_058_[2]),
    .I1(m_araddr[14]),
    .O(m_arvalid[0])
  );
  LUT2 #(
    .INIT(4'h8)
  ) _121_ (
    .I0(_058_[2]),
    .I1(m_araddr[14]),
    .O(m_arvalid[1])
  );
  LUT2 #(
    .INIT(4'h4)
  ) _122_ (
    .I0(_063_[2]),
    .I1(_070_[1]),
    .O(m_awvalid[0])
  );
  LUT2 #(
    .INIT(4'h4)
  ) _123_ (
    .I0(_063_[2]),
    .I1(_069_[1]),
    .O(m_awvalid[1])
  );
  LUT2 #(
    .INIT(4'h2)
  ) _124_ (
    .I0(_060_[2]),
    .I1(_060_[3]),
    .O(m_bready[0])
  );
  LUT2 #(
    .INIT(4'h8)
  ) _125_ (
    .I0(_060_[2]),
    .I1(_060_[3]),
    .O(m_bready[1])
  );
  LUT2 #(
    .INIT(4'h2)
  ) _126_ (
    .I0(_054_[2]),
    .I1(m_araddr[14]),
    .O(m_rready[0])
  );
  LUT2 #(
    .INIT(4'h8)
  ) _127_ (
    .I0(_054_[2]),
    .I1(m_araddr[14]),
    .O(m_rready[1])
  );
  LUT2 #(
    .INIT(4'h4)
  ) _128_ (
    .I0(_062_[2]),
    .I1(_070_[1]),
    .O(m_wvalid[0])
  );
  LUT2 #(
    .INIT(4'h4)
  ) _129_ (
    .I0(_062_[2]),
    .I1(_069_[1]),
    .O(m_wvalid[1])
  );
  LUT2 #(
    .INIT(4'h4)
  ) _130_ (
    .I0(_056_[3]),
    .I1(_056_[4]),
    .O(s_awready)
  );
  LUT2 #(
    .INIT(4'h4)
  ) _131_ (
    .I0(_056_[2]),
    .I1(_056_[4]),
    .O(s_wready)
  );
  LUT4 #(
    .INIT(16'h5030)
  ) _132_ (
    .I0(m_bvalid[1]),
    .I1(m_bvalid[0]),
    .I2(_060_[2]),
    .I3(_060_[3]),
    .O(_065_[0])
  );
  LUT4 #(
    .INIT(16'h0503)
  ) _133_ (
    .I0(m_awready[1]),
    .I1(m_awready[0]),
    .I2(_063_[2]),
    .I3(_060_[3]),
    .O(_064_[2])
  );
  LUT4 #(
    .INIT(16'h5030)
  ) _134_ (
    .I0(m_rvalid[1]),
    .I1(m_rvalid[0]),
    .I2(_054_[2]),
    .I3(m_araddr[14]),
    .O(_058_[4])
  );
  LUT5 #(
    .INIT(32'd87490560)
  ) _135_ (
    .I0(s_wvalid),
    .I1(s_awvalid),
    .I2(_056_[2]),
    .I3(_056_[3]),
    .I4(_056_[4]),
    .O(_066_[2])
  );
  LUT2 #(
    .INIT(4'h4)
  ) _136_ (
    .I0(_060_[3]),
    .I1(_057_[1]),
    .O(_070_[1])
  );
  LUT2 #(
    .INIT(4'h8)
  ) _137_ (
    .I0(_060_[3]),
    .I1(_057_[1]),
    .O(_069_[1])
  );
  INV _138_ (
    .I(_067_),
    .O(_017_)
  );
  INV _139_ (
    .I(rst_n),
    .O(_006_)
  );
  LUT3 #(
    .INIT(8'hf8)
  ) _140_ (
    .I0(s_bready),
    .I1(_067_),
    .I2(_066_[2]),
    .O(_014_)
  );
  LUT3 #(
    .INIT(8'hba)
  ) _141_ (
    .I0(_065_[0]),
    .I1(_064_[2]),
    .I2(_021_),
    .O(_013_)
  );
  LUT4 #(
    .INIT(16'hffc4)
  ) _142_ (
    .I0(_021_),
    .I1(_057_[1]),
    .I2(_064_[2]),
    .I3(_057_[2]),
    .O(_012_)
  );
  LUT3 #(
    .INIT(8'hf4)
  ) _143_ (
    .I0(s_bready),
    .I1(_067_),
    .I2(_061_[2]),
    .O(_011_)
  );
  LUT4 #(
    .INIT(16'hb3a0)
  ) _144_ (
    .I0(s_rready),
    .I1(s_arvalid),
    .I2(_068_),
    .I3(s_arready),
    .O(_010_)
  );
  LUT5 #(
    .INIT(32'd4294922288)
  ) _145_ (
    .I0(m_arready[1]),
    .I1(m_arready[0]),
    .I2(_058_[2]),
    .I3(m_araddr[14]),
    .I4(_059_[4]),
    .O(_008_)
  );
  LUT5 #(
    .INIT(32'd4294942912)
  ) _146_ (
    .I0(m_arready[1]),
    .I1(m_arready[0]),
    .I2(_058_[2]),
    .I3(m_araddr[14]),
    .I4(_058_[4]),
    .O(_009_)
  );
  LUT3 #(
    .INIT(8'hf4)
  ) _147_ (
    .I0(_056_[4]),
    .I1(_057_[1]),
    .I2(_057_[2]),
    .O(_001_)
  );
  LUT3 #(
    .INIT(8'hf4)
  ) _148_ (
    .I0(s_rready),
    .I1(_068_),
    .I2(_055_[2]),
    .O(_007_)
  );
  FDCE #(
    .INIT(1'hx)
  ) _149_ (
    .C(clk),
    .CE(_055_[2]),
    .CLR(_006_),
    .D(_053_),
    .Q(s_rdata[0])
  );
  FDCE #(
    .INIT(1'hx)
  ) _150_ (
    .C(clk),
    .CE(_055_[2]),
    .CLR(_006_),
    .D(_052_),
    .Q(s_rdata[1])
  );
  FDCE #(
    .INIT(1'hx)
  ) _151_ (
    .C(clk),
    .CE(_055_[2]),
    .CLR(_006_),
    .D(_051_),
    .Q(s_rdata[2])
  );
  FDCE #(
    .INIT(1'hx)
  ) _152_ (
    .C(clk),
    .CE(_055_[2]),
    .CLR(_006_),
    .D(_050_),
    .Q(s_rdata[3])
  );
  FDCE #(
    .INIT(1'hx)
  ) _153_ (
    .C(clk),
    .CE(_055_[2]),
    .CLR(_006_),
    .D(_049_),
    .Q(s_rdata[4])
  );
  FDCE #(
    .INIT(1'hx)
  ) _154_ (
    .C(clk),
    .CE(_055_[2]),
    .CLR(_006_),
    .D(_048_),
    .Q(s_rdata[5])
  );
  FDCE #(
    .INIT(1'hx)
  ) _155_ (
    .C(clk),
    .CE(_055_[2]),
    .CLR(_006_),
    .D(_047_),
    .Q(s_rdata[6])
  );
  FDCE #(
    .INIT(1'hx)
  ) _156_ (
    .C(clk),
    .CE(_055_[2]),
    .CLR(_006_),
    .D(_046_),
    .Q(s_rdata[7])
  );
  FDCE #(
    .INIT(1'hx)
  ) _157_ (
    .C(clk),
    .CE(_055_[2]),
    .CLR(_006_),
    .D(_045_),
    .Q(s_rdata[8])
  );
  FDCE #(
    .INIT(1'hx)
  ) _158_ (
    .C(clk),
    .CE(_055_[2]),
    .CLR(_006_),
    .D(_044_),
    .Q(s_rdata[9])
  );
  FDCE #(
    .INIT(1'hx)
  ) _159_ (
    .C(clk),
    .CE(_055_[2]),
    .CLR(_006_),
    .D(_043_),
    .Q(s_rdata[10])
  );
  FDCE #(
    .INIT(1'hx)
  ) _160_ (
    .C(clk),
    .CE(_055_[2]),
    .CLR(_006_),
    .D(_042_),
    .Q(s_rdata[11])
  );
  FDCE #(
    .INIT(1'hx)
  ) _161_ (
    .C(clk),
    .CE(_055_[2]),
    .CLR(_006_),
    .D(_041_),
    .Q(s_rdata[12])
  );
  FDCE #(
    .INIT(1'hx)
  ) _162_ (
    .C(clk),
    .CE(_055_[2]),
    .CLR(_006_),
    .D(_040_),
    .Q(s_rdata[13])
  );
  FDCE #(
    .INIT(1'hx)
  ) _163_ (
    .C(clk),
    .CE(_055_[2]),
    .CLR(_006_),
    .D(_039_),
    .Q(s_rdata[14])
  );
  FDCE #(
    .INIT(1'hx)
  ) _164_ (
    .C(clk),
    .CE(_055_[2]),
    .CLR(_006_),
    .D(_038_),
    .Q(s_rdata[15])
  );
  FDCE #(
    .INIT(1'hx)
  ) _165_ (
    .C(clk),
    .CE(_055_[2]),
    .CLR(_006_),
    .D(_037_),
    .Q(s_rdata[16])
  );
  FDCE #(
    .INIT(1'hx)
  ) _166_ (
    .C(clk),
    .CE(_055_[2]),
    .CLR(_006_),
    .D(_036_),
    .Q(s_rdata[17])
  );
  FDCE #(
    .INIT(1'hx)
  ) _167_ (
    .C(clk),
    .CE(_055_[2]),
    .CLR(_006_),
    .D(_035_),
    .Q(s_rdata[18])
  );
  FDCE #(
    .INIT(1'hx)
  ) _168_ (
    .C(clk),
    .CE(_055_[2]),
    .CLR(_006_),
    .D(_034_),
    .Q(s_rdata[19])
  );
  FDCE #(
    .INIT(1'hx)
  ) _169_ (
    .C(clk),
    .CE(_055_[2]),
    .CLR(_006_),
    .D(_033_),
    .Q(s_rdata[20])
  );
  FDCE #(
    .INIT(1'hx)
  ) _170_ (
    .C(clk),
    .CE(_055_[2]),
    .CLR(_006_),
    .D(_032_),
    .Q(s_rdata[21])
  );
  FDCE #(
    .INIT(1'hx)
  ) _171_ (
    .C(clk),
    .CE(_055_[2]),
    .CLR(_006_),
    .D(_031_),
    .Q(s_rdata[22])
  );
  FDCE #(
    .INIT(1'hx)
  ) _172_ (
    .C(clk),
    .CE(_055_[2]),
    .CLR(_006_),
    .D(_030_),
    .Q(s_rdata[23])
  );
  FDCE #(
    .INIT(1'hx)
  ) _173_ (
    .C(clk),
    .CE(_055_[2]),
    .CLR(_006_),
    .D(_029_),
    .Q(s_rdata[24])
  );
  FDCE #(
    .INIT(1'hx)
  ) _174_ (
    .C(clk),
    .CE(_055_[2]),
    .CLR(_006_),
    .D(_028_),
    .Q(s_rdata[25])
  );
  FDCE #(
    .INIT(1'hx)
  ) _175_ (
    .C(clk),
    .CE(_055_[2]),
    .CLR(_006_),
    .D(_027_),
    .Q(s_rdata[26])
  );
  FDCE #(
    .INIT(1'hx)
  ) _176_ (
    .C(clk),
    .CE(_055_[2]),
    .CLR(_006_),
    .D(_026_),
    .Q(s_rdata[27])
  );
  FDCE #(
    .INIT(1'hx)
  ) _177_ (
    .C(clk),
    .CE(_055_[2]),
    .CLR(_006_),
    .D(_025_),
    .Q(s_rdata[28])
  );
  FDCE #(
    .INIT(1'hx)
  ) _178_ (
    .C(clk),
    .CE(_055_[2]),
    .CLR(_006_),
    .D(_024_),
    .Q(s_rdata[29])
  );
  FDCE #(
    .INIT(1'hx)
  ) _179_ (
    .C(clk),
    .CE(_055_[2]),
    .CLR(_006_),
    .D(_023_),
    .Q(s_rdata[30])
  );
  FDCE #(
    .INIT(1'hx)
  ) _180_ (
    .C(clk),
    .CE(_055_[2]),
    .CLR(_006_),
    .D(_022_),
    .Q(s_rdata[31])
  );
  FDCE #(
    .INIT(1'hx)
  ) _181_ (
    .C(clk),
    .CE(_001_),
    .CLR(_006_),
    .D(_021_),
    .Q(_062_[2])
  );
  FDCE #(
    .INIT(1'hx)
  ) _182_ (
    .C(clk),
    .CE(1'h1),
    .CLR(_006_),
    .D(_004_),
    .Q(s_rvalid)
  );
  FDCE #(
    .INIT(1'hx)
  ) _183_ (
    .C(clk),
    .CE(_002_),
    .CLR(_006_),
    .D(_017_),
    .Q(_056_[2])
  );
  FDCE #(
    .INIT(1'hx)
  ) _184_ (
    .C(clk),
    .CE(_059_[4]),
    .CLR(_006_),
    .D(s_araddr[14]),
    .Q(m_araddr[14])
  );
  FDCE #(
    .INIT(1'hx)
  ) _185_ (
    .C(clk),
    .CE(_071_[3]),
    .CLR(_006_),
    .D(s_awaddr[0]),
    .Q(m_awaddr[0])
  );
  FDCE #(
    .INIT(1'hx)
  ) _186_ (
    .C(clk),
    .CE(_071_[3]),
    .CLR(_006_),
    .D(s_awaddr[1]),
    .Q(m_awaddr[1])
  );
  FDCE #(
    .INIT(1'hx)
  ) _187_ (
    .C(clk),
    .CE(_071_[3]),
    .CLR(_006_),
    .D(s_awaddr[2]),
    .Q(m_awaddr[2])
  );
  FDCE #(
    .INIT(1'hx)
  ) _188_ (
    .C(clk),
    .CE(_071_[3]),
    .CLR(_006_),
    .D(s_awaddr[3]),
    .Q(m_awaddr[3])
  );
  FDCE #(
    .INIT(1'hx)
  ) _189_ (
    .C(clk),
    .CE(_071_[3]),
    .CLR(_006_),
    .D(s_awaddr[4]),
    .Q(m_awaddr[4])
  );
  FDCE #(
    .INIT(1'hx)
  ) _190_ (
    .C(clk),
    .CE(_071_[3]),
    .CLR(_006_),
    .D(s_awaddr[5]),
    .Q(m_awaddr[5])
  );
  FDCE #(
    .INIT(1'hx)
  ) _191_ (
    .C(clk),
    .CE(_071_[3]),
    .CLR(_006_),
    .D(s_awaddr[6]),
    .Q(m_awaddr[6])
  );
  FDCE #(
    .INIT(1'hx)
  ) _192_ (
    .C(clk),
    .CE(_071_[3]),
    .CLR(_006_),
    .D(s_awaddr[7]),
    .Q(m_awaddr[7])
  );
  FDCE #(
    .INIT(1'hx)
  ) _193_ (
    .C(clk),
    .CE(_071_[3]),
    .CLR(_006_),
    .D(s_awaddr[8]),
    .Q(m_awaddr[8])
  );
  FDCE #(
    .INIT(1'hx)
  ) _194_ (
    .C(clk),
    .CE(_071_[3]),
    .CLR(_006_),
    .D(s_awaddr[9]),
    .Q(m_awaddr[9])
  );
  FDCE #(
    .INIT(1'hx)
  ) _195_ (
    .C(clk),
    .CE(_071_[3]),
    .CLR(_006_),
    .D(s_awaddr[10]),
    .Q(m_awaddr[10])
  );
  FDCE #(
    .INIT(1'hx)
  ) _196_ (
    .C(clk),
    .CE(_071_[3]),
    .CLR(_006_),
    .D(s_awaddr[11]),
    .Q(m_awaddr[11])
  );
  FDCE #(
    .INIT(1'hx)
  ) _197_ (
    .C(clk),
    .CE(_071_[3]),
    .CLR(_006_),
    .D(s_awaddr[12]),
    .Q(m_awaddr[12])
  );
  FDCE #(
    .INIT(1'hx)
  ) _198_ (
    .C(clk),
    .CE(_071_[3]),
    .CLR(_006_),
    .D(s_awaddr[13]),
    .Q(m_awaddr[13])
  );
  FDCE #(
    .INIT(1'hx)
  ) _199_ (
    .C(clk),
    .CE(_071_[3]),
    .CLR(_006_),
    .D(s_awaddr[14]),
    .Q(m_awaddr[14])
  );
  FDCE #(
    .INIT(1'hx)
  ) _200_ (
    .C(clk),
    .CE(_057_[2]),
    .CLR(_006_),
    .D(_020_),
    .Q(_060_[3])
  );
  FDCE #(
    .INIT(1'hx)
  ) _201_ (
    .C(clk),
    .CE(1'h1),
    .CLR(_006_),
    .D(_005_),
    .Q(_063_[2])
  );
  FDCE #(
    .INIT(1'hx)
  ) _202_ (
    .C(clk),
    .CE(_061_[2]),
    .CLR(_006_),
    .D(_019_),
    .Q(s_bresp[0])
  );
  FDCE #(
    .INIT(1'hx)
  ) _203_ (
    .C(clk),
    .CE(_061_[2]),
    .CLR(_006_),
    .D(_018_),
    .Q(s_bresp[1])
  );
  FDCE #(
    .INIT(1'hx)
  ) _204_ (
    .C(clk),
    .CE(_000_),
    .CLR(_006_),
    .D(_017_),
    .Q(s_bvalid)
  );
  FDCE #(
    .INIT(1'hx)
  ) _205_ (
    .C(clk),
    .CE(_003_),
    .CLR(_006_),
    .D(_017_),
    .Q(_056_[3])
  );
  FDCE #(
    .INIT(1'hx)
  ) _206_ (
    .C(clk),
    .CE(_072_[3]),
    .CLR(_006_),
    .D(s_wstrb[0]),
    .Q(m_wstrb[0])
  );
  FDCE #(
    .INIT(1'hx)
  ) _207_ (
    .C(clk),
    .CE(_072_[3]),
    .CLR(_006_),
    .D(s_wstrb[1]),
    .Q(m_wstrb[1])
  );
  FDCE #(
    .INIT(1'hx)
  ) _208_ (
    .C(clk),
    .CE(_072_[3]),
    .CLR(_006_),
    .D(s_wstrb[2]),
    .Q(m_wstrb[2])
  );
  FDCE #(
    .INIT(1'hx)
  ) _209_ (
    .C(clk),
    .CE(_072_[3]),
    .CLR(_006_),
    .D(s_wstrb[3]),
    .Q(m_wstrb[3])
  );
  FDCE #(
    .INIT(1'hx)
  ) _210_ (
    .C(clk),
    .CE(_072_[3]),
    .CLR(_006_),
    .D(s_wdata[0]),
    .Q(m_wdata[0])
  );
  FDCE #(
    .INIT(1'hx)
  ) _211_ (
    .C(clk),
    .CE(_072_[3]),
    .CLR(_006_),
    .D(s_wdata[1]),
    .Q(m_wdata[1])
  );
  FDCE #(
    .INIT(1'hx)
  ) _212_ (
    .C(clk),
    .CE(_072_[3]),
    .CLR(_006_),
    .D(s_wdata[2]),
    .Q(m_wdata[2])
  );
  FDCE #(
    .INIT(1'hx)
  ) _213_ (
    .C(clk),
    .CE(_072_[3]),
    .CLR(_006_),
    .D(s_wdata[3]),
    .Q(m_wdata[3])
  );
  FDCE #(
    .INIT(1'hx)
  ) _214_ (
    .C(clk),
    .CE(_072_[3]),
    .CLR(_006_),
    .D(s_wdata[4]),
    .Q(m_wdata[4])
  );
  FDCE #(
    .INIT(1'hx)
  ) _215_ (
    .C(clk),
    .CE(_072_[3]),
    .CLR(_006_),
    .D(s_wdata[5]),
    .Q(m_wdata[5])
  );
  FDCE #(
    .INIT(1'hx)
  ) _216_ (
    .C(clk),
    .CE(_072_[3]),
    .CLR(_006_),
    .D(s_wdata[6]),
    .Q(m_wdata[6])
  );
  FDCE #(
    .INIT(1'hx)
  ) _217_ (
    .C(clk),
    .CE(_072_[3]),
    .CLR(_006_),
    .D(s_wdata[7]),
    .Q(m_wdata[7])
  );
  FDCE #(
    .INIT(1'hx)
  ) _218_ (
    .C(clk),
    .CE(_072_[3]),
    .CLR(_006_),
    .D(s_wdata[8]),
    .Q(m_wdata[8])
  );
  FDCE #(
    .INIT(1'hx)
  ) _219_ (
    .C(clk),
    .CE(_072_[3]),
    .CLR(_006_),
    .D(s_wdata[9]),
    .Q(m_wdata[9])
  );
  FDCE #(
    .INIT(1'hx)
  ) _220_ (
    .C(clk),
    .CE(_072_[3]),
    .CLR(_006_),
    .D(s_wdata[10]),
    .Q(m_wdata[10])
  );
  FDCE #(
    .INIT(1'hx)
  ) _221_ (
    .C(clk),
    .CE(_072_[3]),
    .CLR(_006_),
    .D(s_wdata[11]),
    .Q(m_wdata[11])
  );
  FDCE #(
    .INIT(1'hx)
  ) _222_ (
    .C(clk),
    .CE(_072_[3]),
    .CLR(_006_),
    .D(s_wdata[12]),
    .Q(m_wdata[12])
  );
  FDCE #(
    .INIT(1'hx)
  ) _223_ (
    .C(clk),
    .CE(_072_[3]),
    .CLR(_006_),
    .D(s_wdata[13]),
    .Q(m_wdata[13])
  );
  FDCE #(
    .INIT(1'hx)
  ) _224_ (
    .C(clk),
    .CE(_072_[3]),
    .CLR(_006_),
    .D(s_wdata[14]),
    .Q(m_wdata[14])
  );
  FDCE #(
    .INIT(1'hx)
  ) _225_ (
    .C(clk),
    .CE(_072_[3]),
    .CLR(_006_),
    .D(s_wdata[15]),
    .Q(m_wdata[15])
  );
  FDCE #(
    .INIT(1'hx)
  ) _226_ (
    .C(clk),
    .CE(_072_[3]),
    .CLR(_006_),
    .D(s_wdata[16]),
    .Q(m_wdata[16])
  );
  FDCE #(
    .INIT(1'hx)
  ) _227_ (
    .C(clk),
    .CE(_072_[3]),
    .CLR(_006_),
    .D(s_wdata[17]),
    .Q(m_wdata[17])
  );
  FDCE #(
    .INIT(1'hx)
  ) _228_ (
    .C(clk),
    .CE(_072_[3]),
    .CLR(_006_),
    .D(s_wdata[18]),
    .Q(m_wdata[18])
  );
  FDCE #(
    .INIT(1'hx)
  ) _229_ (
    .C(clk),
    .CE(_072_[3]),
    .CLR(_006_),
    .D(s_wdata[19]),
    .Q(m_wdata[19])
  );
  FDCE #(
    .INIT(1'hx)
  ) _230_ (
    .C(clk),
    .CE(_072_[3]),
    .CLR(_006_),
    .D(s_wdata[20]),
    .Q(m_wdata[20])
  );
  FDCE #(
    .INIT(1'hx)
  ) _231_ (
    .C(clk),
    .CE(_072_[3]),
    .CLR(_006_),
    .D(s_wdata[21]),
    .Q(m_wdata[21])
  );
  FDCE #(
    .INIT(1'hx)
  ) _232_ (
    .C(clk),
    .CE(_072_[3]),
    .CLR(_006_),
    .D(s_wdata[22]),
    .Q(m_wdata[22])
  );
  FDCE #(
    .INIT(1'hx)
  ) _233_ (
    .C(clk),
    .CE(_072_[3]),
    .CLR(_006_),
    .D(s_wdata[23]),
    .Q(m_wdata[23])
  );
  FDCE #(
    .INIT(1'hx)
  ) _234_ (
    .C(clk),
    .CE(_072_[3]),
    .CLR(_006_),
    .D(s_wdata[24]),
    .Q(m_wdata[24])
  );
  FDCE #(
    .INIT(1'hx)
  ) _235_ (
    .C(clk),
    .CE(_072_[3]),
    .CLR(_006_),
    .D(s_wdata[25]),
    .Q(m_wdata[25])
  );
  FDCE #(
    .INIT(1'hx)
  ) _236_ (
    .C(clk),
    .CE(_072_[3]),
    .CLR(_006_),
    .D(s_wdata[26]),
    .Q(m_wdata[26])
  );
  FDCE #(
    .INIT(1'hx)
  ) _237_ (
    .C(clk),
    .CE(_072_[3]),
    .CLR(_006_),
    .D(s_wdata[27]),
    .Q(m_wdata[27])
  );
  FDCE #(
    .INIT(1'hx)
  ) _238_ (
    .C(clk),
    .CE(_072_[3]),
    .CLR(_006_),
    .D(s_wdata[28]),
    .Q(m_wdata[28])
  );
  FDCE #(
    .INIT(1'hx)
  ) _239_ (
    .C(clk),
    .CE(_072_[3]),
    .CLR(_006_),
    .D(s_wdata[29]),
    .Q(m_wdata[29])
  );
  FDCE #(
    .INIT(1'hx)
  ) _240_ (
    .C(clk),
    .CE(_072_[3]),
    .CLR(_006_),
    .D(s_wdata[30]),
    .Q(m_wdata[30])
  );
  FDCE #(
    .INIT(1'hx)
  ) _241_ (
    .C(clk),
    .CE(_072_[3]),
    .CLR(_006_),
    .D(s_wdata[31]),
    .Q(m_wdata[31])
  );
  FDCE #(
    .INIT(1'hx)
  ) _242_ (
    .C(clk),
    .CE(_059_[4]),
    .CLR(_006_),
    .D(s_araddr[0]),
    .Q(m_araddr[0])
  );
  FDCE #(
    .INIT(1'hx)
  ) _243_ (
    .C(clk),
    .CE(_059_[4]),
    .CLR(_006_),
    .D(s_araddr[1]),
    .Q(m_araddr[1])
  );
  FDCE #(
    .INIT(1'hx)
  ) _244_ (
    .C(clk),
    .CE(_059_[4]),
    .CLR(_006_),
    .D(s_araddr[2]),
    .Q(m_araddr[2])
  );
  FDCE #(
    .INIT(1'hx)
  ) _245_ (
    .C(clk),
    .CE(_059_[4]),
    .CLR(_006_),
    .D(s_araddr[3]),
    .Q(m_araddr[3])
  );
  FDCE #(
    .INIT(1'hx)
  ) _246_ (
    .C(clk),
    .CE(_059_[4]),
    .CLR(_006_),
    .D(s_araddr[4]),
    .Q(m_araddr[4])
  );
  FDCE #(
    .INIT(1'hx)
  ) _247_ (
    .C(clk),
    .CE(_059_[4]),
    .CLR(_006_),
    .D(s_araddr[5]),
    .Q(m_araddr[5])
  );
  FDCE #(
    .INIT(1'hx)
  ) _248_ (
    .C(clk),
    .CE(_059_[4]),
    .CLR(_006_),
    .D(s_araddr[6]),
    .Q(m_araddr[6])
  );
  FDCE #(
    .INIT(1'hx)
  ) _249_ (
    .C(clk),
    .CE(_059_[4]),
    .CLR(_006_),
    .D(s_araddr[7]),
    .Q(m_araddr[7])
  );
  FDCE #(
    .INIT(1'hx)
  ) _250_ (
    .C(clk),
    .CE(_059_[4]),
    .CLR(_006_),
    .D(s_araddr[8]),
    .Q(m_araddr[8])
  );
  FDCE #(
    .INIT(1'hx)
  ) _251_ (
    .C(clk),
    .CE(_059_[4]),
    .CLR(_006_),
    .D(s_araddr[9]),
    .Q(m_araddr[9])
  );
  FDCE #(
    .INIT(1'hx)
  ) _252_ (
    .C(clk),
    .CE(_059_[4]),
    .CLR(_006_),
    .D(s_araddr[10]),
    .Q(m_araddr[10])
  );
  FDCE #(
    .INIT(1'hx)
  ) _253_ (
    .C(clk),
    .CE(_059_[4]),
    .CLR(_006_),
    .D(s_araddr[11]),
    .Q(m_araddr[11])
  );
  FDCE #(
    .INIT(1'hx)
  ) _254_ (
    .C(clk),
    .CE(_059_[4]),
    .CLR(_006_),
    .D(s_araddr[12]),
    .Q(m_araddr[12])
  );
  FDCE #(
    .INIT(1'hx)
  ) _255_ (
    .C(clk),
    .CE(_059_[4]),
    .CLR(_006_),
    .D(s_araddr[13]),
    .Q(m_araddr[13])
  );
  FDCE #(
    .INIT(1'hx)
  ) _256_ (
    .C(clk),
    .CE(_055_[2]),
    .CLR(_006_),
    .D(_016_),
    .Q(s_rresp[0])
  );
  FDCE #(
    .INIT(1'hx)
  ) _257_ (
    .C(clk),
    .CE(_055_[2]),
    .CLR(_006_),
    .D(_015_),
    .Q(s_rresp[1])
  );
  FDPE #(
    .INIT(1'hx)
  ) _258_ (
    .C(clk),
    .CE(1'h1),
    .D(_014_),
    .PRE(_006_),
    .Q(_056_[4])
  );
  FDCE #(
    .INIT(1'hx)
  ) _259_ (
    .C(clk),
    .CE(1'h1),
    .CLR(_006_),
    .D(_013_),
    .Q(_060_[2])
  );
  FDCE #(
    .INIT(1'hx)
  ) _260_ (
    .C(clk),
    .CE(1'h1),
    .CLR(_006_),
    .D(_012_),
    .Q(_057_[1])
  );
  FDCE #(
    .INIT(1'hx)
  ) _261_ (
    .C(clk),
    .CE(1'h1),
    .CLR(_006_),
    .D(_011_),
    .Q(_067_)
  );
  FDPE #(
    .INIT(1'hx)
  ) _262_ (
    .C(clk),
    .CE(1'h1),
    .D(_010_),
    .PRE(_006_),
    .Q(s_arready)
  );
  FDCE #(
    .INIT(1'hx)
  ) _263_ (
    .C(clk),
    .CE(1'h1),
    .CLR(_006_),
    .D(_009_),
    .Q(_054_[2])
  );
  FDCE #(
    .INIT(1'hx)
  ) _264_ (
    .C(clk),
    .CE(1'h1),
    .CLR(_006_),
    .D(_008_),
    .Q(_058_[2])
  );
  FDCE #(
    .INIT(1'hx)
  ) _265_ (
    .C(clk),
    .CE(1'h1),
    .CLR(_006_),
    .D(_007_),
    .Q(_068_)
  );
  LUT5 #(
    .INIT(32'd2292890298)
  ) _266_ (
    .I0(s_rvalid),
    .I1(_058_[4]),
    .I2(_054_[2]),
    .I3(s_rready),
    .I4(_068_),
    .O(_004_)
  );
  LUT5 #(
    .INIT(32'd539160354)
  ) _267_ (
    .I0(_063_[2]),
    .I1(_057_[2]),
    .I2(_056_[4]),
    .I3(_057_[1]),
    .I4(_064_[2]),
    .O(_005_)
  );
  assign _059_[3:0] = { m_araddr[14], _058_[2], m_arready[0], m_arready[1] };
  assign _072_[2:0] = { _056_[4], _067_, s_bready };
  assign { _064_[3], _064_[1:0] } = { _057_[2:1], _021_ };
  assign _066_[1:0] = { _067_, s_bready };
  assign { _058_[3], _058_[1:0] } = { m_araddr[14], m_arready[0], m_arready[1] };
  assign { _063_[3], _063_[1:0] } = { _060_[3], m_awready[0], m_awready[1] };
  assign { _062_[4:3], _062_[1:0] } = { _057_[1], _060_[3], m_wready[0], m_wready[1] };
  assign _057_[0] = _056_[4];
  assign _069_[0] = _062_[2];
  assign _056_[1:0] = { s_awvalid, s_wvalid };
  assign _061_[1:0] = { _067_, s_bready };
  assign _055_[1:0] = { _068_, s_rready };
  assign { _054_[3], _054_[1:0] } = { m_araddr[14], m_rvalid[0], m_rvalid[1] };
  assign _060_[1:0] = { m_bvalid[0], m_bvalid[1] };
  assign _065_[2:1] = { _021_, _064_[2] };
  assign _071_[2:0] = { _056_[4], _067_, s_bready };
  assign _070_[0] = _062_[2];
  assign m_araddr[29:15] = m_araddr[14:0];
  assign m_awaddr[29:15] = m_awaddr[14:0];
  assign m_wdata[63:32] = m_wdata[31:0];
  assign m_wstrb[7:4] = m_wstrb[3:0];
endmodule
