// ***************
// Filename: video_processor_tb.sv
// Author: FPGA Cores 4 U
// Description: System testbench of video_processor. Nothing is programmed
//   by the testbench: py_soc boots the firmware (sw/video_proc.py with the
//   CPU initialisation sw/video_init.py, compiled by pyc.py) from a SPI flash model
//   and the firmware brings the system up over its external AXI4-Lite
//   window, reporting every step on UART 0. Reset: arst_n (external) resets
//   the CPU system; the core logic (video) stays in reset until the CPU has
//   booted, passed its self-test and written SYSCTL CORE_RESET
//   (core_rst_n_o, checked by test_core_reset). Board models:
//     - spi_flash_bfm holding the firmware image and string table (pyc.py);
//     - camera module: sensor CCI register model (i2c_bfm, address
//       0x36 on I2C 0) and a CSI-2 RAW10 source (csi2_bfm) that
//       streams 32x24 frames only after the firmware releases its reset
//       (GPIO0[0]) and writes "stream on" (register 0x01 = 1);
//     - I2C EEPROM (i2c_bfm, 0x50 on I2C 1); UART, SPI and GPIO
//       looped back (txd -> rxd, MOSI -> MISO, gpio_o -> gpio_i) for the
//       firmware's peripheral self-test; GPIO0[31] = +quick strap (the
//       firmware then skips the register dumps); GPIO0[30] = image
//       format pin (1 monochrome, 0 colour; the firmware reprograms the ISP
//       on each change and shows the result on GPIO0[2]); GPIO0[29] = image
//       sequence running;
//     - UART 0 receiver: decodes the report at UART_BAUD, writes it to
//       cpu_bootup.txt and echoes each line as "UART0| ...";
//     - HDMI: tmds_serializer lanes deserialised on the TMDS clock lane and
//       decoded by hdmi_bfm; LVDS link A deserialised on the clock
//       lane and decoded as single-link VESA 24 bpp. Their serial clocks and
//       the camera stop after the video checks (the report runs on);
//     - image test: 4 colour and 4 monochrome images (frame_c_<n>_input.ppm,
//       frame_m_<n>_input.ppm in input_images/, generated when missing) are
//       sent by the camera (colour as a Bayer RGGB mosaic) one frame each.
//       The camera paces the sequence so every image flows through the
//       whole pipeline: the next image starts once vision_system has taken
//       the previous one and can take another (vs_stream_adapter would
//       otherwise drop it), and never sooner than the camera's frame gap
//       (CCI registers 0x20-0x21, ns from the end of one frame to the start
//       of the next, power-on value 1280, programmed by the firmware); the
//       format pin for the next image changes as soon as the previous
//       frame's last line is sent. The firmware clears both frame counters
//       once the pipeline is idle, so the sequence is counted from 0 (one
//       frame sent: count 1, all 8 images: 8 at both stages); it reports
//       every end of frame on UART 0 (counts 1, 2, 3, ... at each stage).
//       The frame of each image at the output of every
//       module (csi2_raw_unpack .. isp_csc, vision_system, blur_sharpen, HDMI,
//       LVDS) is saved as output_images/<module>_<c|m>_<n>_output.ppm (P6).
//       Frames are labelled on their way through the pipeline.
//       Plusargs: +IMG_IN_DIR=<dir>, +IMG_OUT_DIR=<dir>.
//   The test tasks are in tests/video_processor_tests.sv (`included).
//   Prints TEST PASSED on success.
// Date: 2026-10-08
`timescale 1ns/1ps
module video_processor_tb;
  `include "video_proc_syms.svh"
  localparam int W = 32, H = 24;
  // Board: 33.333 MHz reference oscillator and the camera's D-PHY byte clock. Every other clock
  // is generated by the DUT (py_soc clock generator): CPU 200 MHz, core 100 MHz, TMDS 1 GHz,
  // LVDS 700 MHz, MIPI TX byte 125 MHz; the firmware turns the display serial clocks on at its
  // video set-up (stage 4). The testbench uses the generated clocks for its models and checks.
  logic ref_clk = 0, byte_clk = 0, arst_n = 0;
  always #15  ref_clk = ~ref_clk;                    // 33.333 MHz
  always #4   byte_clk = ~byte_clk;                  // 125 MHz camera D-PHY byte clock (1 Gbit/s per lane)
  wire cpu_clk = dut.cpu_clk, pix_clk = dut.pix_clk;
  wire tmds_ser_clk = dut.tmds_ser_clk, lvds_ser_clk = dut.lvds_ser_clk;
  bit cam_run = 1;                                   // the camera stops after the video checks
  localparam int UART_BAUD = 6_250_000;              // report speed: the UART allows baud * 16 <= f_clk / 2
  localparam int MIN_PASS = 27;
  localparam logic [3:0] CLK_EN_IDLE = 4'b1001;      // core and MIPI byte clocks only                      // [PASS] lines the firmware report must contain
  int errors = 0;
  initial begin
    #150ms;
    $display("ERROR: simulation timeout (firmware stage %0d)", g(G_stage));
    $display("TEST FAILED");
    $finish;
  end

  // ---------------- DUT ----------------
  logic fl_sclk, fl_cs_n, fl_mosi, fl_miso;
  int fl_wip;
  logic [1:0] uart_txd, scl_o, scl_t, sda_o, sda_t, spi_sclk, spi_mosi;
  logic [3:0] spi_cs_n;
  logic [95:0] gpio_o, gpio_t;
  logic boot_done, boot_err, trap, wdt_reset, sdone, core_rst_n;
  logic [15:0] cam_d;
  logic [1:0] cam_v;
  logic [3:0] tmds_ser;
  logic [4:0] lvds_a_ser, lvds_b_ser;
  logic [15:0] dsi_d, ctx_d;
  logic [1:0] dsi_v, ctx_v;
  logic dsi_req, ctx_req;
  wire  [63:0] sdram_dq;
  wire sd_clk, sd_cke, sd_cs_n, sd_ras_n, sd_cas_n, sd_we_n;
  wire [12:0] sd_a;
  wire [1:0] sd_ba;
  wire [7:0] sd_dqm;
  tri1 sda0, scl0, sda1, scl1;
  wire quick_strap = $test$plusargs("quick");
  bit  mono_sel = 1;                                 // image format pin (GPIO0[30]): 1 monochrome, 0 colour
  bit  seq_active = 0;                               // image sequence pending (GPIO0[29])

  video_processor #(
    .NLANES(2),
    .MAX_W(64),
    .CSI_FIFO(256),
    .OUT_FIFO(512),
    .UART0_BAUD(UART_BAUD),
    .UART1_BAUD(UART_BAUD),
    .I2C0_HZ(2_000_000),
    .I2C1_HZ(2_000_000),
    .SPI0_HZ(10_000_000),
    .SPI1_HZ(10_000_000), // fast rates: short simulation
    .FLASH_CLKDIV(3),
    .PLL_MISMATCH_PPM(20_000)
  ) dut (
    .arst_n,
    .ref_clk,
    .flash_sclk_o(fl_sclk),
    .flash_cs_n_o(fl_cs_n),
    .flash_mosi_o(fl_mosi),
    .flash_miso_i(fl_miso),
    .uart_txd_o(uart_txd),
    .uart_rxd_i(uart_txd),
    .i2c_scl_i({scl1, scl0}),
    .i2c_scl_o(scl_o),
    .i2c_scl_t(scl_t),
    .i2c_sda_i({sda1, sda0}),
    .i2c_sda_o(sda_o),
    .i2c_sda_t(sda_t),
    .spi_sclk_o(spi_sclk),
    .spi_mosi_o(spi_mosi),
    .spi_miso_i(spi_mosi),
    .spi_cs_n_o(spi_cs_n),
    .gpio_i({gpio_o[95:32], quick_strap, mono_sel, seq_active, gpio_o[28:0]}),
    .gpio_o,
    .gpio_t,
    .ext_irq_i(1'b0),
    .boot_done_o(boot_done),
    .boot_err_o(boot_err),
    .cpu_trap_o(trap),
    .wdt_reset_o(wdt_reset),
    .core_rst_n_o(core_rst_n),
`ifdef VP_CSI2_RX
    .byte_clk,
    .cam_lane_data_i(cam_d),
    .cam_lane_valid_i(cam_v),
`endif
`ifdef VP_HDMI
    .tmds_serial_o(tmds_ser),
`endif
`ifdef VP_LVDS
    .lvds_a_serial_o(lvds_a_ser),
    .lvds_b_serial_o(lvds_b_ser),
`endif
`ifdef VP_DSI
    .dsi_lane_data_o(dsi_d),
    .dsi_lane_valid_o(dsi_v),
    .dsi_hs_req_o(dsi_req),
    .dsi_tx_ready_i(1'b0),
`endif
`ifdef VP_CSI2_TX
    .csitx_lane_data_o(ctx_d),
    .csitx_lane_valid_o(ctx_v),
    .csitx_hs_req_o(ctx_req),
    .csitx_tx_ready_i(1'b0),
`endif
`ifdef VP_VISION
    .sdram_clk(sd_clk),
    .sdram_cke(sd_cke),
    .sdram_cs_n(sd_cs_n),
    .sdram_ras_n(sd_ras_n),
    .sdram_cas_n(sd_cas_n),
    .sdram_we_n(sd_we_n),
    .sdram_a(sd_a),
    .sdram_ba(sd_ba),
    .sdram_dqm(sd_dqm),
    .sdram_dq(sdram_dq),
`endif
    .stats_done_o(sdone));
`ifndef VP_HDMI
  assign tmds_ser = '0;
`endif
`ifndef VP_LVDS
  assign lvds_a_ser = '0;
  assign lvds_b_ser = '0;
`endif

  // ---------------- board: flash, I2C, camera ----------------
  spi_flash_bfm flash (
    .sclk(fl_sclk),
    .cs_n(fl_cs_n),
    .mosi(fl_mosi),
    .miso(fl_miso),
    .wip_cycles(fl_wip)
  );
  assign sda0 = sda_t[0] ? 1'bz : sda_o[0];
  assign scl0 = scl_t[0] ? 1'bz : scl_o[0];
  assign sda1 = sda_t[1] ? 1'bz : sda_o[1];
  assign scl1 = scl_t[1] ? 1'bz : scl_o[1];
  i2c_bfm #(.ADDR(7'h36)) sensor_cci (
    .sda(sda0),
    .scl(scl0)
  );
  i2c_bfm #(.ADDR(7'h50)) eeprom (
    .sda(sda1),
    .scl(scl1)
  );
  csi2_bfm #(.NL(2)) cam (
    .clk(byte_clk),
    .lane_data(cam_d),
    .lane_valid(cam_v)
  );

  int raw [H][W];
  initial for (int y = 0; y < H; y++) for (int x = 0; x < W; x++) raw[y][x] = 64 + ((37 * x + 91 * y + 13 * x * y) % 900);
  // Expected output: ISP bypassed (raw value on R, G and B, 10 -> 8 bit), vision_system identity.
  // vision_system's Q16.16 coordinate arithmetic may round a sample by 1 LSB (its own regression
  // accepts max error 1): its output is checked within 1 of this.
  function automatic logic [23:0] ex(input int x, input int y);
    logic [7:0] v;
    v = 8'(raw[y][x] >> 2);
    return {v, v, v};
  endfunction

  // ---------------- image test: inputs, frame labels, module output taps ----------------
  // Label of a frame: 0-3 colour image n, 4-7 monochrome image n, -1 the synthetic raw[][] image.
  localparam int NIMG = 8, NT = 11;
  localparam int T_UNPACK = 0, T_BLC = 1, T_DPC = 2, T_DEMOSAIC = 3, T_CCM = 4, T_GAMMA = 5, T_CSC = 6,
                 T_VISION = 7, T_FILTER = 8, T_HDMI = 9, T_LVDS = 10;
  logic [23:0] in_img [NIMG][H][W];                  // input images {B, G, R}
  logic [23:0] io_img [H][W];                        // PPM read / write buffer
  logic [23:0] tap_img [NT][H][W];                   // frame being captured at each tap
  logic [23:0] out_img [NT][NIMG][H][W];             // first complete frame of each image at each tap
  bit   tap_saved [NT][NIMG];
  int   tap_x [NT], tap_y [NT], tap_lab [NT], tap_done_lab [NT];
  int   lq [NT][16]; // label FIFO towards each tap
  int lq_w [NT], lq_r [NT];
  bit   img_mode = 0;                                // camera: 0 live raw[][] frames, 1 the image sequence
  bit   img_go = 0;                                  // image sequence: start sending (pipeline empty)
  int   img_next = 0;                                // next image of the sequence
  int   vs_f0 = 0;                                   // vs_stream_adapter frames_o when the sequence starts
  string img_in_dir = "input_images", img_out_dir = "output_images";
  initial for (int t = 0; t < NT; t++) begin
    tap_x[t] = 0;
    tap_y[t] = 2 * H;
    tap_lab[t] = -1;
    tap_done_lab[t] = -1;
    lq_w[t] = 0;
    lq_r[t] = 0;
    for (int i = 0; i < NIMG; i++) tap_saved[t][i] = 0;
  end

  // Camera control registers 0x20-0x21: frame gap in ns (end of one frame to the start of the next),
  // power-on value 1280; applied after every frame end packet, in byte clocks (8 ns)
  initial begin
    #1;
    sensor_cci.mem[8'h20] = 8'h05;
    sensor_cci.mem[8'h21] = 8'h00;
  end
  function automatic int frame_gap_ns();
    return {sensor_cci.mem[8'h20], sensor_cci.mem[8'h21]};
  endfunction

  int cam_frames = 0;
  wire cam_on = gpio_o[0] && !gpio_t[0] && sensor_cci.mem[8'h01] == 8'h01;
  initial begin
    wait (cam_on);
    $display("[%t] camera released from reset and streaming (I2C 0x36 reg 0x01 = 1)", $realtime);
    while (cam_run) begin
      int lab;
      if (!img_mode) lab = -1;                         // live: the synthetic raw[][] image
      else if (img_go && img_next < NIMG) begin
`ifdef VP_VISION
        // pace the sequence: the next image once vision_system has taken the previous one and can
        // take another (ready, return FIFO empty), so vs_stream_adapter drops none of them
        if (img_next > 0) begin
          wait (dut.u_vs_adapt.frames_o >= vs_f0 + img_next);
          wait (dut.u_vs_adapt.m_axis_tready && dut.u_vs_adapt.ret_empty);
          @(posedge byte_clk);
        end
`endif
        lab = img_next;
        img_next++;
      end
      else lab = -2;                                   // waiting for the start, or sequence sent: idle
      if (lab == -2) @(posedge byte_clk);
      else begin
        lq_push(T_UNPACK, lab);                        // label of this frame, in camera order
        cam.gap = 4;
        cam.csi_pay.delete();
        cam.csi_packet(2'd0, 6'h00, 16'(cam_frames + 1));
        cam.send_pkt();
        for (int y = 0; y < H; y++) begin
          cam.csi_px.delete();
          for (int x = 0; x < W; x++) cam.csi_px.push_back(lab < 0 ? 10'(raw[y][x]) : sensor_px(lab, x, y));
          cam.csi_pack_raw10();
          cam.csi_packet(2'd0, 6'h2B, 16'(cam.csi_pay.size()));
          cam.gap = 110;
          cam.send_pkt();
        end
        // last line sent: the next image's format goes to the pin now, the firmware reprograms the
        // ISP during the frame gap; after the last image the sequence ends
        if (img_mode && img_next < NIMG) mono_sel = (img_next >= 4);
        if (img_mode && lab == NIMG - 1) seq_active = 0;
        cam.csi_pay.delete();
        cam.csi_packet(2'd0, 6'h01, 16'(cam_frames + 1));
        cam.gap = (frame_gap_ns() + 7) / 8;
        cam.send_pkt();
        cam_frames++;
      end
    end
  end

  // ---------------- HDMI: TMDS lanes -> tmds_bfm (deserialise, LSB first) -> hdmi_bfm (decode) ----------------
  logic [9:0] tw0, tw1, tw2;
  logic trclk, tlocked;
  tmds_bfm tmds (
    .ser_clk(tmds_ser_clk),
    .lanes(tmds_ser),
    .ch0(tw0),
    .ch1(tw1),
    .ch2(tw2),
    .sym_clk(trclk),
    .locked(tlocked)
  );
`ifdef VP_HDMI
  wire sink_en = tlocked;
`else
  wire sink_en = 1'b0;
`endif
  hdmi_bfm #(
    .MAXW(64),
    .MAXH(32)
  ) sink (
    .clk(trclk),
    .en(sink_en),
    .ch0(tw0),
    .ch1(tw1),
    .ch2(tw2)
  );

  // ---------------- LVDS link A: lvds_bfm (deserialise bit 6 first, decode VESA 24 bpp) ----------------
  lvds_bfm #(
    .NDATA(4),
    .MAXW(W),
    .MAXH(H)
  ) lvds (
    .ser_clk(lvds_ser_clk),
    .lanes(lvds_a_ser)
  );
  always @(lvds.frame_done) display_done(T_LVDS);

  // ---------------- firmware globals and traps ----------------
  function automatic longint g(input int idx);
    logic [33:0] v;
    v = dut.u_cpu.u_core.globals[idx];
    return v[0] ? longint'($signed(v) >>> 1) : -999;
  endfunction
  longint last_stage = -1;
  always @(posedge cpu_clk) if (arst_n) begin
    if (g(G_stage) != last_stage) begin
      last_stage = g(G_stage);
      $display("[%t] firmware stage %0d", $realtime, last_stage);
    end
    if (trap) begin
      $display("ERROR @%0t: core trap (see build/fw/video_proc.lst)", $time);
      $display("TEST FAILED");
      $finish;
    end
  end

  // ---------------- vision_system output capture (all frames must be identical: static scene) ----------------
  logic [23:0] vs_frame [H][W];
  logic [23:0] exp_img [H][W];
  int vs_x = 0, vs_y = 0, vs_frames = 0, vs_changes = 0;
  bit vs_diff = 0;
`ifdef VP_VISION
  always @(posedge pix_clk) if (dut.vr_v && dut.vr_r) begin
    if (dut.vr_u) begin
      vs_x = 0;
      vs_y = 0;
      vs_diff = 0;
    end
    if (vs_y < H && vs_x < W) begin
      if (vs_frames > 0 && vs_frame[vs_y][vs_x] !== dut.vr_d) vs_diff = 1;
      vs_frame[vs_y][vs_x] = dut.vr_d;
    end
    if (dut.vr_l) begin
      vs_x = 0;
      vs_y++;
      if (vs_y == H) begin
        if (vs_diff && vs_frames > 0) vs_changes++;
        vs_frames++;
      end
    end else vs_x++;
  end
`endif
  conv2d_ref #(
    .N(5),
    .C(3),
    .CW(8),
    .MAXW(W),
    .MAXH(H)
  ) mdl ();

  // Module output taps (image test). One block, upstream first, so a label is passed on before it is
  // needed downstream. 10-bit components are shown as 8 bits; a raw (Bayer) value as grey.
  always @(posedge pix_clk) begin
    if (dut.u_pipe.u_v && dut.u_pipe.u_r) tap_pixel(T_UNPACK, raw8(dut.u_pipe.u_d), dut.u_pipe.u_l, dut.u_pipe.u_u);
    if (dut.u_pipe.g_v && dut.u_pipe.g_r) tap_pixel(T_BLC, raw8(dut.u_pipe.g_d), dut.u_pipe.g_l, dut.u_pipe.g_u);
    if (dut.u_pipe.p_v && dut.u_pipe.p_r) tap_pixel(T_DPC, raw8(dut.u_pipe.p_d), dut.u_pipe.p_l, dut.u_pipe.p_u);
    if (dut.u_pipe.d_v && dut.u_pipe.d_r) tap_pixel(T_DEMOSAIC, rgb8(dut.u_pipe.d_d), dut.u_pipe.d_l, dut.u_pipe.d_u);
    if (dut.u_pipe.m_v && dut.u_pipe.m_r) tap_pixel(T_CCM, rgb8(dut.u_pipe.m_d), dut.u_pipe.m_l, dut.u_pipe.m_u);
    if (dut.u_pipe.gm_v && dut.u_pipe.gm_r) tap_pixel(T_GAMMA, dut.u_pipe.gm_d, dut.u_pipe.gm_l, dut.u_pipe.gm_u);
    if (dut.u_pipe.cq_v && dut.u_pipe.cq_r) tap_pixel(T_CSC, dut.u_pipe.cq_d, dut.u_pipe.cq_l, dut.u_pipe.cq_u);
`ifdef VP_VISION
    // vs_stream_adapter forwards a frame to vision_system (or drops it): the forwarded frame is the one
    // that last started at the insert point (isp_csc output)
    if (dut.va_v && dut.va_r && dut.va_u) lq_push(T_VISION, tap_lab[T_CSC]);
    if (dut.vr_v && dut.vr_r) tap_pixel(T_VISION, dut.vr_d, dut.vr_l, dut.vr_u);
`endif
`ifdef VP_FILTER
    if (dut.ir_v && dut.ir_r) tap_pixel(T_FILTER, dut.ir_d, dut.ir_l, dut.ir_u);
`endif
  end
  // HDMI: the sink counts a frame at the next frame's vsync edge
  always @(sink.frames) display_done(T_HDMI);

  // ---------------- UART 0 receiver: the firmware report -> cpu_bootup.txt ----------------
  localparam real UART_BIT = 1.0e9 / UART_BAUD;      // ns
  int uart_fd, uart_lines = 0, uart_pass = 0, uart_fail = 0;
  bit uart_end = 0;
  string uart_line = "";
  int rep_first = 0, rep_last = 0, rep_lines = 0;    // last frame counts the CPU reported (section 7)
  int rep_gaps = 0, rep_n;                           // reports that were not the previous count + 1
  string eof_first_txt = "  EOF first stage (interrupt 13): frame count ";
  string eof_last_txt  = "  EOF last stage  (interrupt 14): frame count ";
  uart_bfm #(.BIT_NS(UART_BIT)) uart0 (                // receiver on UART 0 (its rxd is the loopback)
    .txd(),
    .rxd(uart_txd[0])
  );
  initial begin
    uart0.rx_en = 0;
    uart_fd = $fopen("cpu_bootup.txt", "w");
    wait (boot_done);                                  // the line is idle (high) from here
    uart0.rx_en = 1;
  end
  always @(uart0.line_done) begin
    uart_line = uart0.last_line;
    $fwrite(uart_fd, "%s\n", uart_line);
    $fflush(uart_fd);
    $display("UART0| %s", uart_line);
    uart_lines++;
    if (uart_line.len() >= 8 && uart_line.substr(0, 7) == "  [PASS]") uart_pass++;
    if (uart_line.len() >= 8 && uart_line.substr(0, 7) == "  [FAIL]") uart_fail++;
    if (uart_line == "END OF REPORT") uart_end = 1;
    // "  EOF first / last stage (interrupt 13 / 14): frame count <n>" (the CPU's frame count reports)
    if (uart_line.len() > eof_first_txt.len() && uart_line.substr(0, eof_first_txt.len() - 1) == eof_first_txt) begin
      void'($sscanf(uart_line.substr(eof_first_txt.len(), uart_line.len() - 1), "%d", rep_n));
      if (rep_n != rep_first + 1) rep_gaps++;         // counts run 1, 2, 3, ...: one per end of frame
      rep_first = rep_n;
      rep_lines++;
    end
    if (uart_line.len() > eof_last_txt.len() && uart_line.substr(0, eof_last_txt.len() - 1) == eof_last_txt) begin
      void'($sscanf(uart_line.substr(eof_last_txt.len(), uart_line.len() - 1), "%d", rep_n));
      if (rep_n != rep_last + 1) rep_gaps++;
      rep_last = rep_n;
      rep_lines++;
    end
  end

  // ---------------- tests ----------------
  logic [23:0] px, pe;
  bit pok;
  int pd;
  `include "video_processor_tests.sv"

  initial begin
    $timeformat(-6, 1, " us", 10);
    void'($value$plusargs("IMG_IN_DIR=%s", img_in_dir));
    void'($value$plusargs("IMG_OUT_DIR=%s", img_out_dir));
    load_images();                                     // input_images/: read, or generate when missing
    $readmemh(`FW_HEX, flash.mem);
    repeat (5) @(posedge cpu_clk);
    #3 arst_n = 1;
    sink.hdmi = 1;
    sink.vs_active = 1;
    test_boot();
    test_core_reset();
    test_firmware();
    test_vision_output();
    expected_image();
    test_hdmi();
    test_lvds();
    test_adapter();
    test_images();                                     // 4 colour + 4 monochrome images, every module output saved
    // video checked: stop the display serial clocks (SYSCTL CLK_EN forced, simulation speed only)
    // and the camera, then wait for the rest of the firmware report
    force dut.u_cpu.clk_en = CLK_EN_IDLE;
    cam_run = 0;
    $display("[%t] video checks done; serial clocks and camera stopped, waiting for the report", $realtime);
    test_uart_report();
    $fclose(uart_fd);
    if (errors == 0) $display("TEST PASSED");
    else $display("TEST FAILED (%0d errors)", errors);
    $finish;
  end

  // ---------------- waveform dump ----------------
  // +vcd writes video_processor_tb.vcd (scripts/run_sim.sh --vcd / --wave, make wave). A whole run is
  // long: +vcd_start_us=<n> / +vcd_stop_us=<n> limit the dump to a window of simulated time.
  initial if ($test$plusargs("vcd")) begin
    int t_on, t_off;
    t_on = 0;
    t_off = 0;
    void'($value$plusargs("vcd_start_us=%d", t_on));
    void'($value$plusargs("vcd_stop_us=%d", t_off));
    $dumpfile("video_processor_tb.vcd");
    if (t_on > 0) begin
      $dumpvars(0, video_processor_tb);
      $dumpoff;
      #(t_on * 1us);
      $dumpon;
    end
    else $dumpvars(0, video_processor_tb);
    if (t_off > t_on) begin
      #((t_off - t_on) * 1us);
      $dumpoff;
      $dumpflush;
    end
  end
endmodule
