#!/usr/bin/env python3
# ***************
# Filename: update_readme_diagrams.py
# Author: FPGA Cores 4 U
# Description: Adds (or refreshes) a "Diagrams" section in every README.md of
#   the repository, between the markers
#     <!-- diagrams:begin ... -->  and  <!-- diagrams:end -->
#   so re-running only rewrites that block. What each README gets:
#     - an IP's own README: its block / state diagrams (<ip>_block_diagram.svg,
#       <ip>_fsm.svg), RTL hierarchy (block_diagram.svg) and data-flow diagram
#       (<ip>_dataflow.svg, make_dataflow_diagrams.py), embedded;
#     - a category README (ip/<category>/README.md): the hand-drawn block
#       diagrams embedded, and a table linking every IP's diagrams;
#     - ip/README.md: the diagram index of the whole library, by category;
#     - a system README (image_processing/<system>/README.md): the system's
#       diagrams not already shown, its data flow, and its design-local IP;
#     - the repository README: links to the indexes.
#   Diagrams are linked relative to the README, so they render on GitHub.
#   Folders without diagrams (constraints/, include/, testbench helpers) are
#   left alone.
# Date: 2026-10-08
# ***************
"""Usage: python3 ip/scripts/update_readme_diagrams.py [--dry-run]"""
from __future__ import annotations

import argparse
import os
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from make_system_prompt import IP_ROOT, REPO, SYSTEMS_ROOT, discover  # noqa: E402

BEGIN = "<!-- diagrams:begin (generated by ip/scripts/update_readme_diagrams.py; edits here are overwritten) -->"
END = "<!-- diagrams:end -->"
BLOCK_RE = re.compile(r"\n*<!-- diagrams:begin.*?<!-- diagrams:end -->\n*", re.S)
CATEGORY_TITLE = {"cdc": "CDC", "fifo": "FIFO", "cpu": "CPU"}


# ---------------------------------------------------------------- diagrams of one block

def hierarchy_worth_showing(dot: Path) -> bool:
    """block_diagram.svg is the generated RTL hierarchy; a single box adds nothing."""
    return dot.is_file() and len(re.findall(r"\blabel=", dot.read_text(errors="replace"))) >= 3


def diagrams(d: Path, name: str) -> list[tuple[str, Path]]:
    """(caption, svg) of a block's diagrams, most explanatory first."""
    docs = d / "docs"
    out = []
    for svg in sorted(docs.glob(f"{name}*_block_diagram.svg")) + sorted(docs.glob("system_block_diagram.svg")):
        out.append(("Block diagram" if not svg.name.startswith("system") else "System block diagram", svg))
    for svg in sorted(docs.glob(f"{name}*_fsm.svg")):
        out.append(("State machine", svg))
    if (docs / "block_diagram.svg").is_file() and hierarchy_worth_showing(docs / "block_diagram.dot"):
        out.append(("Block diagram" if d.parent == SYSTEMS_ROOT else "RTL hierarchy", docs / "block_diagram.svg"))
    flow = docs / f"{name}_dataflow.svg"
    if flow.is_file():
        out.append(("Data flow", flow))
    return out


def rel(target: Path, readme: Path) -> str:
    return os.path.relpath(target, readme.parent).replace(os.sep, "/")


def embed(caption: str, svg: Path, readme: Path, name: str) -> str:
    r = rel(svg, readme)
    return f"### {caption}\n\n[![{caption} of {name}]({r})]({r})\n"


LEGEND = ("Data-flow diagrams are generated from the RTL by `ip/scripts/make_dataflow_diagrams.py`: inputs on the "
          "left, outputs on the right, registers as double-bordered boxes grouped by the `always` block that drives "
          "them, combinational signals as ellipses, sub-modules in yellow, AXI4-Stream / AXI4 / AXI4-Lite buses as "
          "one teal line. Click a diagram for the full-size SVG.")


# ---------------------------------------------------------------- what the README text already shows

def referenced(readme: Path) -> set[Path]:
    """Diagrams the README's own text (outside the generated block) already shows or names: images, links and
    backticked paths. These are not repeated in the generated section (the text keeps its diagram)."""
    text = BLOCK_RE.sub("\n", readme.read_text(errors="replace"))
    found = set()
    for m in re.finditer(r"\]\(([^)\s#]+\.(?:svg|png))\)|`([^`\s]+\.(?:svg|png))`", text):
        p = (readme.parent / (m.group(1) or m.group(2))).resolve()
        found.add(p.with_suffix(".svg"))
    return found


# ---------------------------------------------------------------- section builders

def ip_section(readme: Path, d: Path, name: str) -> str:
    known = referenced(readme)
    items = [(c, s) for c, s in diagrams(d, name) if s.resolve() not in known]
    if not items:
        return ""
    return "## Diagrams\n\n" + LEGEND + "\n\n" + "\n".join(embed(c, s, readme, f"`{name}`") for c, s in items)


def link_cells(readme: Path, d: Path, name: str, shown: set[Path] = frozenset()) -> list[str]:
    """Links to a block's diagrams; ones already shown on the page (shown) are marked instead of repeated."""
    docs = d / "docs"
    def link(svg: Path, text: str) -> str:
        return f"[{text}]({rel(svg, readme)})" if svg.is_file() else "-"
    blocks = sorted(docs.glob(f"{name}*_block_diagram.svg")) + sorted(docs.glob(f"{name}*_fsm.svg"))
    block = ", ".join(("state machine" if s.stem.endswith("_fsm") else "block") + " (shown above)" if s.resolve() in shown
                      else f"[{'state machine' if s.stem.endswith('_fsm') else 'block'}]({rel(s, readme)})"
                      for s in blocks) or "-"
    hier = link(docs / "block_diagram.svg", "hierarchy") if hierarchy_worth_showing(docs / "block_diagram.dot") else "-"
    return [block, hier, link(docs / f"{name}_dataflow.svg", "data flow")]


def category_section(readme: Path, cat_dir: Path, ips: list) -> str:
    rows, embeds = [], []
    known = referenced(readme)
    shown: set[Path] = set(known)
    for m in sorted(ips, key=lambda m: m.name):
        if not (m.path / "docs").is_dir():
            continue
        for svg in sorted((m.path / "docs").glob(f"{m.name}*_block_diagram.svg")) + sorted((m.path / "docs").glob(f"{m.name}*_fsm.svg")):
            if svg.resolve() in known:
                continue                                 # the README text already shows it
            cap = "state machine" if svg.stem.endswith("_fsm") else "block diagram"
            embeds.append(f"### `{m.name}` {cap}\n\n[![{m.name} {cap}]({rel(svg, readme)})]({rel(svg, readme)})\n")
            shown.add(svg.resolve())
    for m in sorted(ips, key=lambda m: m.name):
        if (m.path / "docs").is_dir():
            rows.append([f"`{m.name}`"] + link_cells(readme, m.path, m.name, shown))
    if not rows:
        return ""
    table = "| IP | Block / state diagrams | RTL hierarchy | Data flow |\n|---|---|---|---|\n" + \
            "\n".join("| " + " | ".join(r) + " |" for r in rows)
    return ("## Diagrams\n\n" + LEGEND + "\n\n" + "\n".join(embeds) + ("\n" if embeds else "")
            + "### Every IP in this category\n\n" + table + "\n")


def library_section(readme: Path, mods: dict) -> str:
    by_cat: dict[str, list] = {}
    for m in mods.values():
        if not m.system and (m.path / "docs").is_dir():
            by_cat.setdefault(m.category, []).append(m)
    parts = ["## Diagrams\n", LEGEND + " Every IP's `docs/` folder holds its diagrams; regenerate them with "
             "`python3 scripts/make_dataflow_diagrams.py` (data flow) and `make -C <category>/<ip> diagrams` (hierarchy).\n"]
    for cat in sorted(by_cat, key=str.casefold):
        title = CATEGORY_TITLE.get(cat, cat.title())
        rows = "\n".join("| " + " | ".join([f"[`{m.name}`]({rel(m.path, readme)})"] + link_cells(readme, m.path, m.name)) + " |"
                         for m in sorted(by_cat[cat], key=lambda m: m.name))
        parts.append(f"### {title}\n\n| IP | Block / state diagrams | RTL hierarchy | Data flow |\n|---|---|---|---|\n{rows}\n")
    return "\n".join(parts)


def system_section(readme: Path, d: Path) -> str:
    known = referenced(readme)
    items = [(c, s) for c, s in diagrams(d, d.name) if s.resolve() not in known]
    parts = ["## Diagrams\n", LEGEND + "\n"]
    parts += [embed(c, s, readme, f"`{d.name}`") for c, s in items]
    subs = sorted(p for p in (d / "ip").iterdir() if (p / "docs").is_dir()) if (d / "ip").is_dir() else []
    if subs:
        rows = "\n".join("| " + " | ".join([f"`{p.name}`"] + link_cells(readme, p, p.name)) + " |" for p in subs)
        parts.append("### Design-local IP\n\n| IP | Block / state diagrams | RTL hierarchy | Data flow |\n|---|---|---|---|\n"
                     + rows + "\n")
    return "\n".join(parts) if len(parts) > 2 else ""


def repo_section(readme: Path) -> str:
    lines = ["## Diagrams\n",
             "Every IP has a data-flow diagram generated from its RTL, plus its RTL hierarchy and, for the CPU, "
             "hand-drawn block and state diagrams:\n",
             f"- [Diagram index of the IP library]({rel(IP_ROOT / 'README.md', readme)}#diagrams)"]
    for sysdir in sorted(p for p in SYSTEMS_ROOT.iterdir() if (p / "README.md").is_file()):
        lines.append(f"- [`{sysdir.name}` diagrams]({rel(sysdir / 'README.md', readme)}#diagrams)")
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------- README editing

def place(text: str, section: str) -> str:
    """Replace the generated block, or insert it before the closing sections (Documentation / License / Design
    notes), or append it."""
    block = f"{BEGIN}\n{section.rstrip()}\n{END}"
    if BLOCK_RE.search(text):
        return BLOCK_RE.sub(lambda _: "\n\n" + block + "\n\n", text, count=1).rstrip() + "\n"
    m = re.search(r"^## (Documentation|License|Design notes)\b", text, re.M)
    if m:
        return text[:m.start()].rstrip() + "\n\n" + block + "\n\n" + text[m.start():]
    return text.rstrip() + "\n\n" + block + "\n"


def main() -> None:
    ap = argparse.ArgumentParser(description="Add / refresh the Diagrams section of every README.md.")
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()
    mods = discover()
    by_path = {m.path.resolve(): m for m in mods.values()}
    cats: dict[str, list] = {}
    for m in mods.values():
        if not m.system:
            cats.setdefault(m.category, []).append(m)

    changed = skipped = 0
    readmes = sorted(p for p in REPO.rglob("README.md") if not {"build", ".git", "node_modules"} & set(p.parts))
    for readme in readmes:
        d = readme.parent.resolve()
        if readme == REPO / "README.md":
            section = repo_section(readme)
        elif d == IP_ROOT.resolve():
            section = library_section(readme, mods)
        elif d.parent == SYSTEMS_ROOT.resolve():
            section = system_section(readme, d)
        elif d.parent == IP_ROOT.resolve() and d.name in cats:
            section = category_section(readme, d, cats[d.name])
        elif d in by_path or (d / "docs" / f"{d.name}_dataflow.svg").is_file():
            section = ip_section(readme, d, d.name)
        else:
            section = ""
        if not section:
            skipped += 1
            print(f"skip   {readme.relative_to(REPO)} (no diagrams)")
            continue
        old = readme.read_text(errors="replace")
        new = place(old, section)
        if new != old:
            changed += 1
            if not args.dry_run:
                readme.write_text(new, encoding="utf-8")
        print(f"{'update' if new != old else 'same  '} {readme.relative_to(REPO)}")
    print(f"{changed} README files updated, {skipped} without diagrams{' (dry run)' if args.dry_run else ''}")


if __name__ == "__main__":
    main()
