../py_core/src/py_core_pkg.sv
../py_core/src/py_core.sv
../../shared/src/common/ip_axil_regs.sv
../../shared/src/fifo/ip_axis_fifo.sv
../../bus/axi4_lite_slave/src/axi4_lite_slave.sv
../../bus/axi4_lite_decoder/src/axi4_lite_decoder.sv
../../peripherals/uart/src/uart_baud.sv
../../peripherals/uart/src/uart_tx.sv
../../peripherals/uart/src/uart_rx.sv
../../peripherals/uart/src/uart_top.sv
../../peripherals/i2c_master/src/i2c_bit_ctrl.sv
../../peripherals/i2c_master/src/i2c_master_fsm.sv
../../peripherals/i2c_master/src/i2c_top.sv
../../peripherals/spi_master/src/spi_engine.sv
../../peripherals/spi_master/src/spi_top.sv
../../peripherals/gpio/src/gpio_top.sv
../../peripherals/intc/src/intc_top.sv
../../timing/watchdog/src/watchdog_top.sv
src/py_stream_port.sv
src/py_axil_xbar.sv
../../peripherals/spi_flash_ctrl/src/spi_flash_ctrl.sv
src/py_boot.sv
src/py_sysctl.sv
src/py_soc.sv
